{
  "hash": "9d5d74e0ef6fc504fcd0df10532110da",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take Home Exercise 1\"\nsubtitle: \"Diagnosing Loss Drivers in a Spanish Motor Portfolio\"\nauthor: \"Yap Jit Wei\"\ndate: \"May 20, 2026\"\ndate-modified: \"last-modified\"\n\nformat:\n  html:\n    toc: true\n    toc-depth: 4\n    number-sections: true\n    code-fold: true\n    code-summary: \"Show the code\"\n    \nexecute:\n  warning: false \n  freeze: auto\n---\n\n\n\n# Overview\n\n## Setting the scene\n\nProperty and casualty insurance portfolios routinely underperform without the insurer being able to diagnose why. Loss-driving pockets hide inside coarse segments. Mispriced coverage tiers persist because no one has visualised the loss-ratio gap. Premium inadequacy in narrow sub-books goes undetected until a bad year exposes it.\n\n::: callout-note\n\"Insurers often carry underperforming portfolios where the root causes of poor profitability and high volatility are unknown. Leveraging visual analytics can potentially help investigate trends in underlying loss drivers, while data enrichment using external data can help refine segmentation and underwriting strategy.\"\n\nSwiss Re Institute (2019), *sigma 4/2019: Advanced analytics: unlocking new frontiers in P&C insurance*\n:::\n\nMotor insurance is a particularly fertile setting for visual analytics. Premiums are exposure-weighted. Claims arrive frequently enough to support statistical inference at the segment level. A loss-ratio improvement of two to five percentage points, achievable through better segmentation alone, can move a motor book between profit and loss.\n\n## Analytical objectives\n\nThis report applies visual analytics to a Spanish motor vehicle insurance portfolio with two objectives:\n\n1.  **Univariate analysis**: characterise the distribution of the portfolio's numerical and categorical variables, surfacing concentration, skewness, and structural features that inform downstream segmentation.\n\n2.  **Bivariate analysis with statistical validation**: investigate the factors influencing portfolio profitability (proxied by loss ratio) and volatility (proxied by the coefficient of variation of loss ratio across policies within a segment), with statistical validation of the observed patterns.\n\nBeyond this scope, the analysis applies three visual analytics methods that sit outside Lessons 1 to 5, selected to leverage features of the dataset that standard univariate and bivariate methods cannot reach.\n\n## Dataset\n\nThe data is a real-world Spanish motor insurance portfolio published through Mendeley Data, comprising 354,140 policy-year records across 185,678 unique policyholders between 2022 and 2024. The dataset contains 47 variables organised into four logical groups:\n\n-   **Policy and insured characteristics**: `policy_type`, `bonus_score`, `business_type`, `payment_frequency`, and the observation year.\n-   **Driver and vehicle characteristics**: `driver_age`, `vehicle_age`, `fuel_type`, `vehicle_value`, `power_to_weight_ratio`, `circulation_area`, and others.\n-   **Premiums**: `total_premium` and seven coverage-specific premiums (liability, property damage, theft, fire, glass, legal protection, occupants).\n-   **Exposure, claim counts, and incurred costs**: total and per coverage.\n\nThe granularity of premium and incurred figures permits coverage-specific loss-ratio decomposition in addition to portfolio-level analysis. This level of detail is uncommon in publicly available motor insurance datasets, and the report exploits it where it adds analytical leverage.\n\n::: callout-note\n**Reproducibility**: The raw data file (`Dataset of motor insurance portfolio.csv`, approximately 90MB) exceeds GitHub's recommended file size limit and is therefore excluded from this repository via `.gitignore`. To reproduce the analysis, download the dataset from Mendeley Data and place it in the `Data/` folder at the project root. The analytical sandbox (`motor_clean.rds`) is generated on first render by the code in Section 2 and does not need to be committed.\n:::\n\n## Report structure\n\nSection 2 documents the analytical sandbox preparation: import, cleaning, type encoding, and derivation of the profitability and volatility variables. Section 3 presents the univariate distributional analysis. Section 4 examines bivariate relationships with statistical validation of the observed effects. Section 5 introduces three visual analytics methods that extend beyond the techniques covered in class. Section 6 summarises the key findings and identifies directions for future research.\n\n# Analytical sandbox preparation\n\n## Loading R packages\n\nThe analytical pipeline relies on the tidyverse for data wrangling, several ggplot2 extensions for visualisation, and supporting packages for table presentation. Each package is selected for a specific role. The rationale is summarised below.\n\n| Package       | Purpose                                                |\n|---------------|--------------------------------------------------------|\n| `tidyverse`   | Core wrangling and visualisation grammar               |\n| `readxl`      | Reading the data dictionary `.xlsx`                    |\n| `janitor`     | Variable name cleaning and duplicate detection         |\n| `skimr`       | Compact summary of numerical and categorical variables |\n| `naniar`      | Visualising missingness patterns                       |\n| `ggstatsplot` | Statistical test annotations on plots                  |\n| `ggdist`      | Uncertainty and distribution geoms                     |\n| `ggridges`    | Ridgeline density plots                                |\n| `ggcorrplot`  | Correlation matrix visualisation                       |\n| `ggalluvial`  | Sankey and alluvial flow diagrams                      |\n| `ggdendro`    | Dendrogram extraction for ggplot2-based cluster heatmap|\n| `ggrepel`     | Non-overlapping text labels                            |\n| `patchwork`   | Composite plot layouts                                 |\n| `scales`      | Axis formatting (percent, comma, currency)             |\n| `knitr`       | Table rendering                                        ||\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(tidyverse, readxl, janitor, skimr, naniar,\n               ggstatsplot, ggdist, ggridges,\n               ggcorrplot, ggalluvial, ggdendro, ggrepel,\n               patchwork, scales, knitr)\n```\n:::\n\n\n\n### Design principles for chart styling\n\nA consistent visual language across the report's charts makes the analytical content easier to follow. Four design principles are encoded into a custom theme function (`theme_house()`) and a four-colour palette, applied to charts built directly in ggplot2.\n\nTwo exceptions apply. Charts produced by ggstatsplot inherit the package's default styling, since the wrapper exposes limited theming hooks; the focal colour is overridden where the package permits. Categorical flow visualisations (the Sankey in Section 5.1) map distinct colours to each category by necessity, where blue indicates positive bonus-malus standing rather than functioning as a default fill.\n\n\nThe four principles are:\n\n1. **One focal colour for the data point under discussion.** A single red (`#C44E52`) marks the segment, year, or category being discussed in the surrounding prose. All other elements use grey to recede visually, so the reader's eye is directed without ambiguity.\n2. **Reference values in muted grey.** Benchmarks (the 70% loss-ratio line, the portfolio mean CV, the break-even threshold) use a mid-grey so they sit behind the data without competing for attention.\n3. **Diverging palette only where direction matters.** Loss-ratio heatmaps use the RdYlBu diverging palette, which encodes the analyst's break-even threshold visually. Univariate distributions use a single blue fill, since no direction is being encoded.\n4. **Finding-led titles, descriptive subtitles.** Chart titles state the headline finding (\"COMP_N runs at 93.5% loss ratio\") rather than describing the chart type. The subtitle below names the underlying variables and population.\n\nThe four colour constants are factored out of the theme so they can be referenced by name in any chart, which keeps the palette consistent and reduces a palette change to a one-line edit.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheme_house <- function(base_size = 11) {\n  theme_minimal(base_size = base_size) +\n    theme(\n      plot.title = element_text(face = \"bold\", size = base_size + 2),\n      plot.subtitle = element_text(colour = \"grey40\",\n                                   size = base_size - 1,\n                                   margin = margin(b = 10)),\n      plot.caption = element_text(colour = \"grey50\",\n                                  size = base_size - 3,\n                                  hjust = 0),\n      panel.grid.major.x = element_blank(),\n      panel.grid.minor = element_blank(),\n      axis.text = element_text(size = base_size - 2),\n      axis.title = element_text(size = base_size - 1.5),\n      axis.title.x = element_text(margin = margin(t = 8)),\n      axis.title.y = element_text(margin = margin(r = 8)),\n      plot.margin = margin(t = 10, r = 15, b = 15, l = 10),\n      legend.position = \"top\",\n      legend.title = element_text(size = base_size - 2, face = \"bold\"),\n      legend.text = element_text(size = base_size - 2)\n    )\n}\n\n\nhouse_highlight <- \"#C44E52\"      \nhouse_muted     <- \"grey75\"       \nhouse_benchmark <- \"grey40\"       \nhouse_sequential <- \"RdYlBu\"     \n```\n:::\n\n\n\n\n## Importing the raw data\n\nThe portfolio file is a semicolon-delimited CSV using European decimal conventions. The companion data dictionary is a small Excel workbook documenting variable meanings and units, used as a reference during encoding decisions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw <- read_delim(\"Data/Dataset of motor insurance portfolio.csv\",\n                  delim = \";\", show_col_types = FALSE) |>\n  clean_names()\n\ndict <- read_excel(\"Data/Descriptive of variables.xlsx\") |>\n  clean_names()\n```\n:::\n\n\n`clean_names()` from **janitor** standardises column names to snake_case, removing the need for backtick-escaping downstream.\n\n## Initial inspection\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(raw)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 354,140\nColumns: 47\n$ insured_id                  <dbl> 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, …\n$ year                        <dbl> 2022, 2022, 2023, 2024, 2022, 2023, 2024, …\n$ policy_type                 <chr> \"COMP_E\", \"COMP_E\", \"COMP_E\", \"COMP_E\", \"C…\n$ policy_status               <chr> \"C\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A…\n$ business_type               <chr> \"NB\", \"P\", \"P\", \"P\", \"NB\", \"P\", \"P\", \"NB\",…\n$ payment_frequency           <chr> \"A\", \"A\", \"A\", \"A\", \"S\", \"S\", \"S\", \"A\", \"A…\n$ bonus_score                 <chr> \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G…\n$ driver_age                  <dbl> 48, 43, 44, 45, 45, 46, 47, 32, 33, 34, 39…\n$ vehicle_age                 <dbl> 22, 24, 25, 26, 26, 27, 28, 12, 13, 14, 20…\n$ age_driving_licence         <dbl> 26, 19, 19, 18, 19, 19, 19, 19, 19, 19, 19…\n$ fuel_type                   <chr> \"G\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D…\n$ vehicle_value               <dbl> 149511.44, 65065.12, 65065.12, 65065.12, 5…\n$ seats                       <dbl> 4, 8, 8, 8, 7, 7, 7, 5, 5, 5, 5, 5, 5, 5, …\n$ power_to_weight_ratio       <dbl> 3.92, 10.15, 10.15, 10.15, 9.19, 9.19, 9.1…\n$ vehicle_brand               <chr> \"PORSCHE\", \"MERCEDES\", \"MERCEDES\", \"MERCED…\n$ municipality_type           <chr> \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I…\n$ circulation_area            <chr> \"U\", \"U\", \"U\", \"U\", \"R\", \"R\", \"R\", \"R\", \"R…\n$ total_premium               <dbl> 279.5576, 546.6234, 548.7526, 584.6324, 68…\n$ liability_premium           <dbl> 30.60232, 114.33336, 110.66689, 122.09253,…\n$ property_damage_premium     <dbl> 121.9127, 303.1060, 304.9560, 305.2251, 35…\n$ theft_premium               <dbl> 112.361489, 80.784824, 83.521384, 107.8868…\n$ fire_premium                <dbl> 3.832441, 7.826861, 6.151465, 5.842892, 7.…\n$ glass_premium               <dbl> 8.305788, 30.091751, 32.861626, 31.101584,…\n$ legal_protection_premium    <dbl> 2.043622, 7.812747, 7.655637, 10.084173, 6…\n$ occupants_premium           <dbl> 0.4992053, 2.6679084, 2.9395659, 2.3992827…\n$ total_claims                <dbl> 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, …\n$ liability_claims            <dbl> 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ liability_property_claims   <dbl> 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ liability_injury_claims     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ property_claims             <dbl> 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, …\n$ theft_claims                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ fire_claims                 <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ glass_claims                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ legal_protection_claims     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ occupants_claims            <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ total_incurred              <dbl> 0.000, 0.000, 233.013, 2586.361, 0.000, 0.…\n$ liability_incurred          <dbl> 0.000, 0.000, 233.013, 1035.000, 0.000, 0.…\n$ liability_property_incurred <dbl> 0.000, 0.000, 233.013, 1035.000, 0.000, 0.…\n$ liability_injury_incurred   <dbl> 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, …\n$ property_incurred           <dbl> 0.000, 0.000, 0.000, 1551.361, 0.000, 0.00…\n$ theft_incurred              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ fire_incurred               <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ glass_incurred              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ legal_protection_incurred   <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ occupants_incurred          <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ total_exposure              <dbl> 0.09863014, 1.00000000, 1.00000000, 1.0000…\n$ liability_exposure          <dbl> 0.09863014, 1.00000000, 1.00000000, 1.0000…\n```\n\n\n:::\n:::\n\n\nThe portfolio contains 354,140 policy-year records across 47 variables. Each record is one policy-year, meaning a single policyholder may appear in multiple rows if their policy spans 2022, 2023, and 2024. This panel structure is preserved for the bivariate analysis in Section 4 and exploited for the bonus analysis in Section 5.\n\n### Duplicates\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw |> \n  get_dupes() |> \n  nrow()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\nNo exact duplicates were detected.\n\n### Missingness\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngg_miss_var(raw, show_pct = TRUE)\n```\n\n::: {.cell-output-display}\n![Missing value patterns across the portfolio.](TH_EX01_report_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nFour variables contain missing values. `fuel_type` (1,287 missing, 0.36%) and `vehicle_value` (513 missing, 0.14%) account for nearly all of it. The remaining columns have two or fewer NAs each. Because missingness is concentrated in non-target descriptive variables and represents under half a percent of records, listwise deletion is acceptable without introducing meaningful selection bias.\n\nBefore applying listwise deletion, the records flagged for removal are profiled against the records to be retained, to verify that deletion does not introduce systematic bias.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw_check <- read_delim(\"Data/Dataset of motor insurance portfolio.csv\",\n                        delim = \";\", show_col_types = FALSE) |>\n  janitor::clean_names()\n\nraw_check |>\n  mutate(dropped = is.na(fuel_type) | is.na(vehicle_value)) |>\n  group_by(dropped) |>\n  summarise(\n    n              = n(),\n    mean_premium   = mean(total_premium, na.rm = TRUE),\n    mean_incurred  = mean(total_incurred, na.rm = TRUE),\n    mean_exposure  = mean(total_exposure, na.rm = TRUE),\n    claim_rate     = mean(total_claims > 0),\n    .groups = \"drop\"\n  ) |>\n  mutate(dropped = if_else(dropped, \"Dropped\", \"Retained\")) |>\n  kable(\n    caption = \"Profile comparison: records flagged for deletion versus records retained\",\n    digits = c(0, 0, 2, 2, 4, 4),\n    format.args = list(big.mark = \",\")\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Profile comparison: records flagged for deletion versus records retained\n\n|dropped  |       n| mean_premium| mean_incurred| mean_exposure| claim_rate|\n|:--------|-------:|------------:|-------------:|-------------:|----------:|\n|Retained | 352,340|       296.25|        208.36|        0.7069|     0.1433|\n|Dropped  |   1,800|       388.55|        251.52|        0.6965|     0.1833|\n\n\n:::\n:::\n\n\n\nThe dropped and retained groups differ modestly on three of the four metrics. The 1,800 records flagged for deletion show 31% higher mean premium, 21% higher mean incurred losses, and a 4-percentage-point higher claim rate than the retained records. Mean exposure is essentially identical. This indicates that the missingness in `fuel_type` and `vehicle_value` is not completely at random; the affected records skew toward higher-premium, claim-bearing policies. Listwise deletion is retained as the simplest defensible treatment given the small proportion involved (0.51%), but the resulting analysis applies to the 352,340-record retained population. Findings should not be extrapolated to the dropped sub-population, which may behave somewhat differently.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw <- raw |> drop_na(fuel_type, vehicle_value)\n```\n:::\n\n\nThe two patterns of missingness are non-overlapping. No row has both `fuel_type` and `vehicle_value` missing, so listwise deletion removes exactly 1,800 records without any compounding effect.\n\n## Variable encoding\n\nCategorical variables are imported as character vectors. Converting them to factors with explicit, meaningful level ordering improves both downstream plot readability and statistical test behaviour.\n\nTwo ordering choices warrant explanation. The `policy_type` levels are ordered from least to most comprehensive coverage (TP, TPG, CC, COMP_E, COMP_N), enabling monotonic interpretation of loss-ratio gradients across coverage tiers. The `bonus_score` levels are ordered from best to worst claim history (G, N, B), following the bonus-malus convention used by motor insurers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclean <- raw |>\n  mutate(\n    year             = as.integer(year),\n    policy_type      = factor(policy_type,\n                              levels = c(\"TP\",\"TPG\",\"CC\",\"COMP_E\",\"COMP_N\")),\n    policy_status    = factor(policy_status, levels = c(\"A\",\"C\"),\n                              labels = c(\"Active\",\"Cancelled\")),\n    business_type    = factor(business_type, levels = c(\"NB\",\"P\"),\n                              labels = c(\"New business\",\"Persistent\")),\n    payment_frequency = factor(payment_frequency, levels = c(\"A\",\"S\",\"Q\"),\n                               labels = c(\"Annual\",\"Semi-annual\",\"Quarterly\")),\n    bonus_score      = factor(bonus_score, levels = c(\"G\",\"N\",\"B\"),\n                              labels = c(\"Good\",\"Neutral\",\"Bad\")),\n    fuel_type        = factor(fuel_type, levels = c(\"D\",\"G\"),\n                              labels = c(\"Diesel\",\"Gasoline\")),\n    municipality_type = factor(municipality_type, levels = c(\"I\",\"C\",\"IS\"),\n                               labels = c(\"Interior\",\"Coastal\",\"Islands\")),\n    circulation_area = factor(circulation_area, levels = c(\"U\",\"R\"),\n                              labels = c(\"Urban\",\"Rural\"))\n  )\n```\n:::\n\n\n## Sanity checks\n\nBefore deriving the analytical variables, the cleaned dataset is checked for out-of-range values, logical inconsistencies, and internal consistency between totals and their components.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclean |>\n  summarise(\n    driver_age_oob   = sum(driver_age < 18 | driver_age > 100, na.rm = TRUE),\n    vehicle_age_neg  = sum(vehicle_age < 0, na.rm = TRUE),\n    premium_neg      = sum(total_premium < 0, na.rm = TRUE),\n    incurred_neg     = sum(total_incurred < 0, na.rm = TRUE),\n    claims_neg       = sum(total_claims < 0, na.rm = TRUE),\n    exposure_oob     = sum(total_exposure < 0 | total_exposure > 1, na.rm = TRUE),\n    exposure_zero    = sum(total_exposure == 0, na.rm = TRUE),\n    incurred_no_claim = sum(total_claims == 0 & total_incurred > 0),\n    claim_no_incurred = sum(total_claims > 0 & total_incurred == 0)\n  ) |>\n  kable(caption = \"Sanity checks on potentially impossible values\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Sanity checks on potentially impossible values\n\n| driver_age_oob| vehicle_age_neg| premium_neg| incurred_neg| claims_neg| exposure_oob| exposure_zero| incurred_no_claim| claim_no_incurred|\n|--------------:|---------------:|-----------:|------------:|----------:|------------:|-------------:|-----------------:|-----------------:|\n|              0|               0|           0|            0|          0|            0|            49|                 0|              8498|\n\n\n:::\n:::\n\n\nMost checks return zero, indicating no out-of-range or logically inconsistent values across age, premium, and claim-count variables. Two findings warrant comment:\n\n- **49 policy-years (0.01%) have zero exposure**, representing policies that did not go on risk during their observation year, most likely from same-day cancellations or administrative records with immediately-closed exposure windows. The derived `claim_frequency` variable is computed conditionally on `total_exposure > 0`, returning `NA` for these records, so they do not distort downstream frequency calculations.\n\n- **8,498 policy-years (2.4%) have a recorded claim count but zero incurred losses.** This is a known pattern in motor insurance data, arising from claims that are opened and later closed at zero cost (denial, withdrawal, or below-deductible settlement) or claims still open at the year-end extraction. These records are retained: they contribute to claim frequency but not to incurred losses, which is the appropriate treatment.\n\n`total_exposure` is bounded above by 1 in all 352,340 records, confirming the variable's intended semantics as the fraction of the policy-year on risk.\nA second consistency check verifies that the seven coverage-specific premium and claim columns sum exactly to `total_premium` and `total_claims`. Any mismatch would indicate a data assembly error in the source file.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclean |>\n  summarise(\n    claims_sum_mismatch = sum(\n      abs(total_claims - (liability_claims + property_claims + theft_claims +\n                          fire_claims + glass_claims + legal_protection_claims +\n                          occupants_claims)) > 0\n    ),\n    premium_sum_mismatch = sum(\n      abs(total_premium - (liability_premium + property_damage_premium +\n                            theft_premium + fire_premium + glass_premium +\n                            legal_protection_premium + occupants_premium)) > 0.01\n    )\n  ) |>\n  kable(caption = \"Cross-checks between totals and component sums\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Cross-checks between totals and component sums\n\n| claims_sum_mismatch| premium_sum_mismatch|\n|-------------------:|--------------------:|\n|                   0|                    0|\n\n\n:::\n:::\n\n\nBoth checks return zero. The seven coverage-specific columns sum exactly to the totals across all 352,340 records, confirming internal consistency. The coverage decomposition used in downstream analysis is therefore reliable.\n\nA third check examines whether cancelled policies are evenly distributed across coverage tiers. Cancellation truncates the exposure window: a cancelled policy may have accumulated claims and incurred losses against only a partial premium. If cancellations were concentrated in one segment, that segment's loss ratio could be biased.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclean |>\n  group_by(policy_type, policy_status) |>\n  summarise(n = n(), .groups = \"drop\") |>\n  pivot_wider(names_from = policy_status, values_from = n, values_fill = 0) |>\n  mutate(\n    total = Active + Cancelled,\n    cancel_rate = Cancelled / total\n  ) |>\n  kable(\n    caption = \"Cancellation rate by coverage tier\",\n    digits = c(0, 0, 0, 0, 4),\n    format.args = list(big.mark = \",\")\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Cancellation rate by coverage tier\n\n|policy_type |  Active| Cancelled|   total| cancel_rate|\n|:-----------|-------:|---------:|-------:|-----------:|\n|TP          |   5,039|       662|   5,701|      0.1161|\n|TPG         |  30,552|     5,436|  35,988|      0.1511|\n|CC          | 180,824|    23,494| 204,318|      0.1150|\n|COMP_E      |  83,009|     7,311|  90,320|      0.0809|\n|COMP_N      |  14,759|     1,254|  16,013|      0.0783|\n\n\n:::\n:::\n\n\nThe cancellation rate ranges from 7.8% in COMP_N to 15.1% in TPG. The two most comprehensive tiers (COMP_E and COMP_N) show the lowest cancellation rates in the portfolio. This is important for the bivariate analysis: COMP_N's elevated loss ratio (93.5%, reported in Section 4.3) cannot be explained by partial-premium bias from cancellation truncation, since COMP_N policies are the most stable in the book. The finding that COMP_N is structurally mispriced therefore holds independently of cancellation effects. TPG carries the highest cancellation rate at 15.1%, which is worth noting but does not affect the headline findings, since TPG sits in the middle of the loss-ratio distribution rather than at the extremes.\n\nA final check verifies the integrity of `insured_id`, since the Sankey transition analysis in Section 5.1 treats it as a stable policyholder key over time.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclean |>\n  summarise(\n    id_missing      = sum(is.na(insured_id) | insured_id == 0),\n    id_year_dupes   = sum(duplicated(paste(insured_id, year))),\n    max_records_per_id = max(table(insured_id)),\n    distinct_ids    = n_distinct(insured_id)\n  ) |>\n  kable(caption = \"Policyholder identifier integrity\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Policyholder identifier integrity\n\n| id_missing| id_year_dupes| max_records_per_id| distinct_ids|\n|----------:|-------------:|------------------:|------------:|\n|          0|             0|                  3|       184725|\n\n\n:::\n:::\n\n\nAll checks return clean values. No insured_id is missing or zero. No insured_id appears more than once in the same year, confirming the panel is uniquely keyed by (insured_id, year). The maximum number of records per insured_id is three, consistent with the 2022 to 2024 observation window. The 352,340 records correspond to 184,725 distinct policyholders, with an average of 1.9 policy-year observations each. The Sankey analysis in Section 5.1 can therefore treat insured_id as a reliable policyholder identifier.\n\n## Derived analytical variables\n\nThe brief identifies portfolio profitability and volatility as the outcomes of interest, but neither exists in the raw data. Both must be derived from the relationship between premiums collected, losses incurred, and policy exposure. Three policy-level metrics form the foundation:\n\n-   **Loss ratio**: incurred losses divided by earned premium. The industry-standard measure of pure underwriting profitability before expense loading. A loss ratio below approximately 70% indicates a contribution to operating profit on a motor book.\n-   **Claim frequency**: claim count divided by exposure (in policy-years). Exposure-normalising is essential because most policies in this dataset are on-risk for only part of the year (mean exposure 0.71).\n-   **Claim severity**: incurred losses divided by claim count, defined only where claims occurred.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclean <- clean |>\n  mutate(\n    loss_ratio      = if_else(total_premium > 0,\n                              total_incurred / total_premium, NA_real_),\n    claim_frequency = if_else(total_exposure > 0,\n                              total_claims / total_exposure, NA_real_),\n    claim_severity  = if_else(total_claims > 0,\n                              total_incurred / total_claims, NA_real_)\n  )\n```\n:::\n\n\nThree additional banded variables are constructed to support bivariate segmentation. Bands use breaks informed by the underlying distributions (verified in Section 3) and motor underwriting practice.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclean <- clean |> \n  mutate(\n    driver_age_band = cut(driver_age,\n                          breaks = c(0, 25, 35, 50, 65, Inf),\n                          labels = c(\"<25\",\"25-34\",\"35-49\",\"50-64\",\"65+\"),\n                          right = FALSE),\n    vehicle_age_band = cut(vehicle_age,\n                           breaks = c(-1, 2, 5, 10, 15, Inf),\n                           labels = c(\"0-2\",\"3-5\",\"6-10\",\"11-15\",\"16+\"),\n                           right = TRUE),\n    vehicle_value_band = cut(vehicle_value,\n                             breaks = quantile(vehicle_value,\n                                               probs = c(0, .25, .5, .75, 1),\n                                               na.rm = TRUE),\n                             labels = c(\"Q1\",\"Q2\",\"Q3\",\"Q4\"),\n                             include.lowest = TRUE)\n  )\n```\n:::\n\n\nThe band cutoffs are reported below for transparency. Driver-age and vehicle-age bands use hardcoded breaks aligned with actuarial convention and depreciation milestones respectively; vehicle-value bands are computed as quartiles of the observed distribution.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbind_rows(\n  tibble(\n    variable = \"driver_age_band\",\n    breaks = \"0 / 25 / 35 / 50 / 65 / Inf\",\n    rationale = \"Actuarial convention: <25 is the conventional high-risk band; 65+ is the standard senior threshold\"\n  ),\n  tibble(\n    variable = \"vehicle_age_band\",\n    breaks = \"0 / 3 / 6 / 11 / 16 / Inf\",\n    rationale = \"Aligned with depreciation and warranty milestones\"\n  ),\n  tibble(\n    variable = \"vehicle_value_band\",\n    breaks = paste(round(quantile(clean$vehicle_value,\n                                   probs = c(0, .25, .5, .75, 1),\n                                   na.rm = TRUE)), collapse = \" / \"),\n    rationale = \"Quartiles of the observed distribution; vehicle value spans several orders of magnitude\"\n  )\n) |>\n  kable(caption = \"Band definitions used for downstream segmentation\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Band definitions used for downstream segmentation\n\n|variable           |breaks                                |rationale                                                                                          |\n|:------------------|:-------------------------------------|:--------------------------------------------------------------------------------------------------|\n|driver_age_band    |0 / 25 / 35 / 50 / 65 / Inf           |Actuarial convention: <25 is the conventional high-risk band; 65+ is the standard senior threshold |\n|vehicle_age_band   |0 / 3 / 6 / 11 / 16 / Inf             |Aligned with depreciation and warranty milestones                                                  |\n|vehicle_value_band |1630 / 18583 / 24687 / 32228 / 374034 |Quartiles of the observed distribution; vehicle value spans several orders of magnitude            |\n\n\n:::\n:::\n\n\n\n## Volatility metric\n\nVolatility is operationalised at the segment level as the coefficient of variation (CV) of loss ratio across the policies within a segment. Unlike standard deviation, CV is scale-free, making it directly comparable across segments with very different loss-ratio means. A high CV indicates that a segment's profitability is unstable. Even if its mean loss ratio is acceptable, the distribution of individual-policy outcomes is wide, raising the risk of unexpected losses in any given year.\n\nThis summary is computed on demand within the bivariate analysis (Section 4) rather than added to the policy-level data frame, as it is inherently a group-level statistic.\n\n## Saving the analytical sandbox\n\nThe cleaned, encoded, and enriched dataset is written to disk as a single `.rds` file. The slides deliverable consumes the same file, ensuring perfect consistency between report and presentation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(clean, \"Data/motor_clean.rds\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclean |> \n  summarise(\n    records = n(),\n    policyholders = n_distinct(insured_id),\n    years_covered = paste(range(year), collapse = \"–\"),\n    total_premium = sum(total_premium),\n    total_incurred = sum(total_incurred),\n    portfolio_loss_ratio = total_incurred / total_premium\n  ) |>\n  kable(caption = \"Analytical sandbox summary\",\n        format.args = list(big.mark = \",\"))\n```\n\n::: {.cell-output-display}\n\n\nTable: Analytical sandbox summary\n\n| records| policyholders|years_covered | total_premium| total_incurred| portfolio_loss_ratio|\n|-------:|-------------:|:-------------|-------------:|--------------:|--------------------:|\n| 352,340|       184,725|2022–2024     |   104,380,281|     73,412,081|            0.7033137|\n\n\n:::\n:::\n\n\n## Wrangling flowchart\n\nThe figure below summarises the analytical-sandbox preparation pipeline.\n\n```{mermaid}\nflowchart LR\n  A[Raw CSV<br/>354,140 × 47] --> B[clean_names<br/>snake_case]\n  D[Data dictionary<br/>.xlsx] -.reference.-> B\n  B --> C[Drop NA<br/>fuel_type, vehicle_value]\n  C --> E[Factor encoding<br/>8 categoricals]\n  E --> F[Derive KPIs<br/>loss_ratio, frequency, severity]\n  F --> G[Band continuous<br/>driver/vehicle age, value]\n  G --> H[(motor_clean.rds<br/>352,340 × 53)]\n```\n\n# Univariate visual analysis\n\n## Methodology\n\nUnivariate analysis serves two purposes in this exercise. First, it documents the shape of each variable, including central tendency, spread, skewness, and modality, which constrains the techniques available for bivariate analysis. Second, it surfaces concentrations and outliers that often turn out to be the loss drivers the brief asks the analyst to identify.\n\nTwo visual conventions are used:\n\n-   **Continuous variables**: a histogram paired with a horizontal boxplot via the `patchwork` package. The histogram shows distribution shape. The boxplot makes outliers and the five-number summary explicit. The composite is a more honest representation than either alone.\n-   **Categorical variables**: an ordered bar chart with frequency labels. Ordering by frequency (rather than alphabetical or factor-default) reveals concentration immediately, with the most common category at the top.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclean <- read_rds(\"Data/motor_clean.rds\")\n```\n:::\n\n\n## Continuous variables\n\n### Driver age\n\n\n::: {.cell}\n\n```{.r .cell-code}\nh_age <- ggplot(clean, aes(x = driver_age)) +\n  geom_histogram(bins = 40, fill = \"#4C72B0\", colour = \"white\") +\n  scale_y_continuous(labels = comma, expand = expansion(mult = c(0, 0.05))) +\n  labs(x = NULL, y = \"Number of policies\") +\n  theme_house(base_size = 11) +\n  theme(axis.text.x = element_blank(),\n        axis.ticks.x = element_blank())\n\nb_age <- ggplot(clean, aes(x = driver_age)) +\n  geom_boxplot(fill = \"#4C72B0\", colour = \"grey30\",\n               width = 0.5, outlier.alpha = 0.1) +\n  scale_y_continuous(breaks = NULL) +\n  labs(x = \"Driver age (years)\", y = NULL) +\n  theme_house(base_size = 11) +\n  theme(axis.text.y = element_blank())\n\n(h_age / b_age + plot_layout(heights = c(4, 1))) +\n  plot_annotation(\n    title = \"Driver age ranges from 22 to 82, centred in mid-40s\",\n    subtitle = \"Distribution of driver age across 352,340 policy-years\",\n    caption = \"Source: Spanish motor insurance portfolio (Mendeley Data).\",\n    theme = theme(\n      plot.title = element_text(face = \"bold\", size = 13),\n      plot.subtitle = element_text(colour = \"grey40\", size = 10,\n                                   margin = margin(b = 10)),\n      plot.caption = element_text(colour = \"grey50\", size = 8, hjust = 0)\n    )\n  )\n```\n\n::: {.cell-output-display}\n![](TH_EX01_report_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\nThe driver-age distribution spans 22 to 82 years, centred in the mid-40s, with a modest right tail of older drivers. The under-25 segment is small in volume but structurally important: it is the conventional high-risk pool in motor underwriting and becomes a focal point of the bivariate analysis. The 65+ tail is similarly relevant, as senior drivers carry distinct accident-risk profiles.\n\n### Vehicle age\n\n\n::: {.cell}\n\n```{.r .cell-code}\nh_va <- ggplot(clean, aes(x = vehicle_age)) +\n  geom_histogram(bins = 30, fill = \"#4C72B0\", colour = \"white\") +\n  scale_y_continuous(labels = comma, expand = expansion(mult = c(0, 0.05))) +\n  labs(x = NULL, y = \"Number of policies\") +\n  theme_house(base_size = 11) +\n  theme(axis.text.x = element_blank(),\n        axis.ticks.x = element_blank())\n\nb_va <- ggplot(clean, aes(x = vehicle_age)) +\n  geom_boxplot(fill = \"#4C72B0\", colour = \"grey30\",\n               width = 0.5, outlier.alpha = 0.1) +\n  scale_y_continuous(breaks = NULL) +\n  labs(x = \"Vehicle age (years)\", y = NULL) +\n  theme_house(base_size = 11) +\n  theme(axis.text.y = element_blank())\n\n(h_va / b_va + plot_layout(heights = c(4, 1))) +\n  plot_annotation(\n    title = \"Most insured vehicles are between 18 and 36 years old\",\n    subtitle = \"Distribution of vehicle age across 352,340 policy-years\",\n    caption = \"Source: Spanish motor insurance portfolio (Mendeley Data).\",\n    theme = theme(\n      plot.title = element_text(face = \"bold\", size = 13),\n      plot.subtitle = element_text(colour = \"grey40\", size = 10,\n                                   margin = margin(b = 10)),\n      plot.caption = element_text(colour = \"grey50\", size = 8, hjust = 0)\n    )\n  )\n```\n\n::: {.cell-output-display}\n![](TH_EX01_report_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\nThe vehicle-age distribution spans 0 to about 60 years, with most vehicles concentrated between 18 and 36 years old (the IQR) and a median around 25 years. This is an unusually aged portfolio: the bulk of insured vehicles are over 15 years old, with a long tail of vehicles older than 40. The shape suggests two underwriting considerations. Theft exposure tends to concentrate in newer, higher-value vehicles, of which this portfolio has few. Breakdown and mechanical-failure claims rise with vehicle age, which this portfolio has in abundance. These tensions surface in the bivariate analysis of coverage tier and in the driver-age × vehicle-age risk surface.\n\n### Vehicle value\n\n\n::: {.cell}\n\n```{.r .cell-code}\nh_vv <- ggplot(clean, aes(x = vehicle_value)) +\n  geom_histogram(bins = 50, fill = \"#4C72B0\", colour = \"white\") +\n  scale_x_log10(labels = label_currency(prefix = \"€\", scale = 1e-3,\n                                         suffix = \"k\")) +\n  scale_y_continuous(labels = comma, expand = expansion(mult = c(0, 0.05))) +\n  labs(x = NULL, y = \"Number of policies\") +\n  theme_house(base_size = 11) +\n  theme(axis.text.x = element_blank(),\n        axis.ticks.x = element_blank())\n\nb_vv <- ggplot(clean, aes(x = vehicle_value)) +\n  geom_boxplot(fill = \"#4C72B0\", colour = \"grey30\",\n               width = 0.5, outlier.alpha = 0.1) +\n  scale_x_log10(labels = label_currency(prefix = \"€\", scale = 1e-3,\n                                         suffix = \"k\")) +\n  scale_y_continuous(breaks = NULL) +\n  labs(x = \"Vehicle value (€, log scale)\", y = NULL) +\n  theme_house(base_size = 11) +\n  theme(axis.text.y = element_blank())\n\n(h_vv / b_vv + plot_layout(heights = c(4, 1))) +\n  plot_annotation(\n    title = \"Vehicle value clusters around €20-30k with a heavy upper tail\",\n    subtitle = \"Distribution of vehicle value across 352,340 policy-years (log scale)\",\n    caption = \"Source: Spanish motor insurance portfolio (Mendeley Data).\\nLog scale used to reveal the central distribution; the small fraction of high-value vehicles extends beyond €100k.\",\n    theme = theme(\n      plot.title = element_text(face = \"bold\", size = 13),\n      plot.subtitle = element_text(colour = \"grey40\", size = 10,\n                                   margin = margin(b = 10)),\n      plot.caption = element_text(colour = \"grey50\", size = 8, hjust = 0)\n    )\n  )\n```\n\n::: {.cell-output-display}\n![](TH_EX01_report_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\nVehicle value is right-skewed, with the bulk of policies covering vehicles worth between €20,000 and €30,000 and a small share covering higher-value vehicles above €100,000. The log-scale histogram makes the central concentration visible; on a linear scale, the rare high-value outliers would compress the typical distribution into the left edge. This concentration in mid-value vehicles is consistent with the older fleet composition described above.\n\n### Power-to-weight ratio\n\n\n::: {.cell}\n\n```{.r .cell-code}\nh_pw <- ggplot(clean, aes(x = power_to_weight_ratio)) +\n  geom_histogram(bins = 50, fill = \"#4C72B0\", colour = \"white\") +\n  scale_x_log10() +\n  scale_y_continuous(labels = comma, expand = expansion(mult = c(0, 0.05))) +\n  labs(x = NULL, y = \"Number of policies\") +\n  theme_house(base_size = 11) +\n  theme(axis.text.x = element_blank(),\n        axis.ticks.x = element_blank())\n\nb_pw <- ggplot(clean, aes(x = power_to_weight_ratio)) +\n  geom_boxplot(fill = \"#4C72B0\", colour = \"grey30\",\n               width = 0.5, outlier.alpha = 0.1) +\n  scale_x_log10() +\n  scale_y_continuous(breaks = NULL) +\n  labs(x = \"Power-to-weight ratio (log scale)\", y = NULL) +\n  theme_house(base_size = 11) +\n  theme(axis.text.y = element_blank())\n\n(h_pw / b_pw + plot_layout(heights = c(4, 1))) +\n  plot_annotation(\n    title = \"Most vehicles have a power-to-weight ratio between 10 and 15\",\n    subtitle = \"Distribution of power-to-weight ratio across 352,340 policy-years (log scale)\",\n    caption = \"Source: Spanish motor insurance portfolio (Mendeley Data).\",\n    theme = theme(\n      plot.title = element_text(face = \"bold\", size = 13),\n      plot.subtitle = element_text(colour = \"grey40\", size = 10,\n                                   margin = margin(b = 10)),\n      plot.caption = element_text(colour = \"grey50\", size = 8, hjust = 0)\n    )\n  )\n```\n\n::: {.cell-output-display}\n![](TH_EX01_report_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\nPower-to-weight ratio is right-skewed on the raw scale and approximately log-normal once transformed. Most vehicles fall in the 10-15 range, with a long upper tail of high-performance vehicles and a smaller tail at the low end. The upper tail carries the underwriting risk concern: power-to-weight correlates with claim frequency and severity in motor portfolios, and a small number of high-performance policies can disproportionately affect segment-level loss ratios.\n\n## Categorical variables\n\n### Policy type\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(clean, aes(x = fct_infreq(policy_type))) +\n  geom_bar(fill = \"#4C72B0\", colour = \"white\") +\n  geom_text(stat = \"count\",\n            aes(label = comma(after_stat(count))),\n            vjust = -0.4, size = 3.2, colour = \"grey30\") +\n  scale_y_continuous(labels = comma, expand = expansion(mult = c(0, 0.15))) +\n  labs(\n    title = \"Most policies cluster in the mid-comprehensive tier (CC)\",\n    subtitle = \"Distribution of Policy Type across 352,340 policy-years\",\n    x = NULL,\n    y = \"Number of policies\",\n    caption = \"Source: Spanish motor insurance portfolio (Mendeley Data).\"\n  ) +\n  theme_house(base_size = 11)\n```\n\n::: {.cell-output-display}\n![](TH_EX01_report_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\nThe portfolio is dominated by the two combined tiers: CC (204,318 policies, around 58%) and COMP_E (90,320 policies, around 26%). The third-party tiers (TP and TPG) together account for around 12% of policies, and COMP_N (comprehensive without excess) is a small but consequential segment at around 5%. As Section 4 shows, COMP_N carries by far the highest loss intensity relative to premium charged, while CC and COMP_E sit closer to the portfolio benchmark.\n\n### Bonus-Malus Category\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(clean, aes(x = fct_infreq(bonus_score))) +\n  geom_bar(fill = \"#4C72B0\", colour = \"white\") +\n  geom_text(stat = \"count\",\n            aes(label = comma(after_stat(count))),\n            vjust = -0.4, size = 3.2, colour = \"grey30\") +\n  scale_y_continuous(labels = comma, expand = expansion(mult = c(0, 0.15))) +\n  labs(\n    title = \"97% of policy-years are in the Good bonus-malus category\",\n    subtitle = \"Distribution of bonus-malus category across 352,340 policy-years\",\n    x = NULL,\n    y = \"Number of policies\",\n    caption = \"Source: Spanish motor insurance portfolio (Mendeley Data).\"\n  ) +\n  theme_house(base_size = 11)\n```\n\n::: {.cell-output-display}\n![](TH_EX01_report_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\nThe bonus-malus distribution is extreme: 96.5% of policy-years sit in the Good category, with Neutral (2.2%) and Bad (1.3%) together accounting for the remaining 3.5%. The two smaller categories are sufficient in absolute volume for statistical testing (several thousand records each) but small in relative terms. This imbalance becomes important in Section 4.4, where the analysis shows that the small Neutral pool carries a disproportionate share of the portfolio's loss-ratio deterioration.\n\n### Other categoricals\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat_vars <- c(\"policy_status\", \"business_type\", \"payment_frequency\",\n              \"fuel_type\", \"municipality_type\", \"circulation_area\")\n\ncat_summary <- clean |>\n  select(all_of(cat_vars)) |>\n  pivot_longer(everything(), names_to = \"variable\", values_to = \"value\") |>\n  count(variable, value) |>\n  group_by(variable) |>\n  mutate(pct = n / sum(n)) |>\n  ungroup() |>\n  mutate(variable = factor(variable,\n                            levels = cat_vars,\n                            labels = c(\"Policy status\",\n                                       \"Business type\",\n                                       \"Payment frequency\",\n                                       \"Fuel type\",\n                                       \"Municipality type\",\n                                       \"Circulation area\")))\n\nggplot(cat_summary, aes(x = fct_reorder(value, n), y = n)) +\n  geom_col(fill = \"#4C72B0\") +\n  geom_text(aes(label = percent(pct, accuracy = 0.1)),\n            hjust = -0.1, size = 2.8, colour = \"grey30\") +\n  scale_y_continuous(labels = comma, expand = expansion(mult = c(0, 0.2))) +\n  coord_flip() +\n  facet_wrap(~ variable, scales = \"free\", ncol = 2) +\n  labs(\n    title = \"Most categorical variables are heavily concentrated in their dominant category\",\n    subtitle = \"Distribution of six categorical variables across 352,340 policy-years\",\n    x = NULL,\n    y = \"Number of policies\",\n    caption = \"Source: Spanish motor insurance portfolio (Mendeley Data).\\nPercentages are within-variable; bars within each facet are sorted by frequency.\"\n  ) +\n  theme_house(base_size = 11) +\n  theme(\n    strip.text = element_text(face = \"bold\", colour = \"grey20\", size = 10),\n    strip.background = element_rect(fill = \"grey95\", colour = NA),\n    panel.grid.major.y = element_blank(),\n    panel.spacing = unit(1.2, \"lines\")\n  )\n```\n\n::: {.cell-output-display}\n![](TH_EX01_report_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\nSeveral concentrations are worth noting. The portfolio is predominantly new business (69%) rather than persistent renewals (31%), pointing to rapid book growth across the period. New business typically carries higher loss ratios than renewals because insurers price renewals more precisely from claims history, so a fast-growing book can deteriorate even without underlying segment changes. Annual payment dominates over instalment options. Diesel vehicles outnumber gasoline by roughly two to one. Urban and rural circulation are close to balanced (54% vs 46%), though within-category loss-ratio profiles differ markedly as Section 4.5 shows. Interior locations dominate the geographic distribution (65%), with coastal and islands together accounting for 35%; despite their smaller volume, the islands segment carries the widest within-category loss-ratio spread.\n\n## Distribution of derived KPIs\n\nThe three derived KPIs are themselves variables worth profiling. At the policy level, they are highly skewed: most policies have no claims, so most loss ratios and frequencies are zero. Restricting the view to policies with at least one claim reveals the within-distribution shape that matters for segment-level analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshare_above_be <- clean |>\n  filter(total_claims > 0, is.finite(loss_ratio)) |>\n  summarise(share = mean(loss_ratio > 1)) |>\n  pull(share)\n\nclean |>\n  filter(total_claims > 0, is.finite(loss_ratio),\n         loss_ratio >= 0.01, loss_ratio <= 100) |>\n  ggplot(aes(x = loss_ratio, fill = loss_ratio > 1)) +\n  geom_histogram(bins = 50, boundary = 1, colour = \"white\") +\n  scale_x_continuous(\n    trans  = \"log10\",\n    breaks = c(0.01, 0.1, 1, 10, 100),\n    labels = c(\"1%\", \"10%\", \"100%\", \"1,000%\", \"10,000%\")\n  ) +\n  scale_y_continuous(labels = comma, expand = expansion(mult = c(0, 0.12))) +\n  scale_fill_manual(\n    values = c(\"FALSE\" = house_muted, \"TRUE\" = house_highlight),\n    guide  = \"none\"\n  ) +\n  geom_vline(xintercept = 1, linetype = \"dashed\", colour = house_benchmark) +\n  annotate(\n    \"text\",\n    x = 1.15, y = Inf,\n    label  = \"Break-even (100%)\",\n    hjust  = 0, vjust = 1.2,\n    colour = house_benchmark, size = 3.2\n  ) +\n  labs(\n    title    = \"A substantial share of claim-bearing policies exceed break-even\",\n    subtitle = paste0(\n      scales::percent(share_above_be, accuracy = 0.1),\n      \" of claim-bearing policy-years have losses exceeding their premium\"\n    ),\n    x       = \"Loss ratio (log scale)\",\n    y       = \"Policy-years\",\n    caption = \"Source: Spanish motor insurance portfolio (Mendeley Data).\"\n  ) +\n  theme_house()\n```\n\n::: {.cell-output-display}\n![](TH_EX01_report_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\nAmong policies with at least one claim, the loss-ratio distribution spans nearly four orders of magnitude. The dashed grey line marks the break-even point where losses equal premium. The red bars to the right represent policy-years that returned more in claims than they collected in premium. Segment-level mean loss ratios mask this within-policy variance, which is what the volatility (coefficient of variation) analysis in Section 4 surfaces.\n\n\n## Summary of univariate observations\n\nThe univariate view raises three structural features the bivariate analysis must contend with:\n\n1.  **Strong distributional skew** in vehicle value and the derived KPIs. Linear-scale plots will mislead. Log scales and percentile bands are appropriate.\n2.  **Heavy class imbalance** in `bonus_score` (concentrated in Good) and `policy_type` (concentrated in CC and COMP_E). Statistical tests must account for unequal group sizes.\n3.  **The zero-claim majority**. Roughly 85% of policy-years have no claims, making policy-level loss ratio a noisy individual measure but a clean segment-level one when aggregated by exposure-weighted sums.\n\n## Pairwise relationships among continuous variables\n\nBefore turning to bivariate analysis of the categorical risk drivers, the continuous variables are examined jointly through a correlation matrix. The correlogram surfaces three things: which variable pairs move together strongly enough to constrain interpretation downstream, which appear independent and can be treated as separate signals, and whether any pair carries multicollinearity that would distort multivariate inference.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncont_vars <- clean |>\n  select(driver_age, vehicle_age, age_driving_licence,\n         vehicle_value, seats, power_to_weight_ratio,\n         total_premium, total_exposure, loss_ratio) |>\n  filter(if_all(everything(), is.finite))\n\ncorr_matrix <- cor(cont_vars, use = \"pairwise.complete.obs\",\n                   method = \"spearman\")\n\np_matrix <- cor_pmat(cont_vars, method = \"spearman\")\n\nggcorrplot(corr_matrix,\n           type = \"lower\",\n           lab = TRUE,\n           lab_size = 3,\n           p.mat = p_matrix,\n           sig.level = 0.05,\n           insig = \"blank\",\n           colors = c(\"#4C72B0\", \"white\", house_highlight),\n           outline.color = \"white\",\n           tl.cex = 9) +\n  labs(\n    title = \"Driver age and licence tenure are the strongest pair\",\n    subtitle = \"Spearman correlations among continuous variables; non-significant cells (p ≥ 0.05) blanked\",\n    x = NULL, y = NULL,\n    fill = \"Spearman ρ\",\n    caption = \"Source: Spanish motor insurance portfolio (Mendeley Data).\\nSpearman rank correlation used because several variables are heavily skewed.\"\n  ) +\n  theme_house(base_size = 10) +\n  theme(panel.grid = element_blank(),\n        legend.position = \"right\",\n        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),\n        plot.margin = margin(t = 10, r = 15, b = 30, l = 30))\n```\n\n::: {.cell-output-display}\n![](TH_EX01_report_files/figure-html/unnamed-chunk-29-1.png){width=768}\n:::\n:::\n\n\nThree patterns are visible. The strongest correlation in the matrix is between driver_age and age_driving_licence (ρ = 0.86), which is structural and expected: older drivers have held licences longer. A second strong association sits between total_premium and total_exposure (ρ = 0.74), also structural, since premium earned scales with the on-risk period of a policy. The most analytically interesting cell is the moderate negative correlation between vehicle_value and power_to_weight_ratio (ρ = -0.5), indicating that higher-value vehicles in this portfolio tend to be heavier sedans rather than performance vehicles, the opposite of the pattern in younger, sportier markets. Beyond these three, all remaining pairs are weak. loss_ratio in particular shows only weak correlations with the underlying predictors, confirming that no single continuous variable explains policy-level loss outcomes on its own. This is the empirical motivation for the segment-level bivariate analysis that follows: where individual continuous variables fail to discriminate, categorical and joint structure may succeed.\n\n\n# Bivariate visual analysis with statistical validation\n\n## Methodology\n\nThe bivariate analysis investigates how the portfolio's policy, vehicle, driver, and geographic characteristics relate to its profitability (loss ratio) and volatility (coefficient of variation of loss ratio across policies within a segment).\n\nFour analytical principles guide the work:\n\n1.  **Segment-level loss ratio, not policy-level**. Individual policies have highly skewed loss ratios, since most are zero and a few are very large. Aggregating to the segment level via `sum(total_incurred) / sum(total_premium)` produces the exposure-weighted metric an underwriter would price against.\n2.  **Statistical validation alongside every visual claim**. Where the relationship is categorical, `ggstatsplot::ggbetweenstats` or `ggbarstats` provides inline test annotations (ANOVA, Kruskal-Wallis, chi-square). Where the comparison is across years on a ratio of sums, bootstrap confidence intervals are used because the sampling distribution of a ratio is not well-described by closed-form parametric tests.\n3.  **Volatility reported alongside profitability**. A segment with high mean loss ratio is unprofitable. A segment with high CV of loss ratio is unpredictable. Underwriting interventions for these two cases differ and should not be conflated.\n4. **Multiple-comparison correction is applied within tests, not across the report.** The pairwise comparisons within each `ggstatsplot::ggbetweenstats` and `ggbarstats` call use false discovery rate (FDR) adjustment. No correction is applied across the report-wide family of tests. Given the sample size (>350,000 records) and the magnitude of the effects discussed, the substantive findings are robust to multiple-comparison concerns, but readers interpreting individual p-values should bear the report-wide test count in mind.\n\n\n\n## Temporal trajectory\n\nThe first question to ask of any insurance portfolio is whether the recent loss experience is stable, improving, or worsening. The aggregate view by year shows clear movement.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nyr <- clean |>\n  group_by(year) |>\n  summarise(\n    premium  = sum(total_premium),\n    incurred = sum(total_incurred),\n    exposure = sum(total_exposure),\n    claims   = sum(total_claims),\n    n_pol    = n(),\n    .groups  = \"drop\"\n  ) |>\n  mutate(\n    loss_ratio = incurred / premium,\n    frequency  = claims / exposure,\n    severity   = incurred / claims\n  )\n\nyr |>\n  select(year, n_pol, premium, incurred, loss_ratio, frequency, severity) |>\n  kable(\n    caption = \"Portfolio KPIs by year\",\n    digits = c(0, 0, 0, 0, 4, 4, 0),\n    format.args = list(big.mark = \",\")\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Portfolio KPIs by year\n\n|  year|   n_pol|    premium|   incurred| loss_ratio| frequency| severity|\n|-----:|-------:|----------:|----------:|----------:|---------:|--------:|\n| 2,022|  66,890| 18,596,245| 12,219,605|     0.6571|    0.3022|      969|\n| 2,023| 118,265| 35,126,365| 23,372,409|     0.6654|    0.3048|      935|\n| 2,024| 167,185| 50,657,672| 37,820,067|     0.7466|    0.3107|      971|\n\n\n:::\n:::\n\n\nThree movements show up at once. Loss ratio rose from approximately 66% in 2022 to 75% in 2024, a 9-percentage-point swing in two years. Frequency edged up modestly. Severity increased more meaningfully, indicating that average claim cost rather than claim count is the principal driver. To establish whether this trajectory is real or a small-sample artefact, the bootstrap distribution of loss ratio is computed for each year.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(608)\nB <- 500\n\nboot_one_year <- function(df, B) {\n  n <- nrow(df)\n  prem <- df$total_premium\n  inc  <- df$total_incurred\n  replicate(B, {\n    idx <- sample.int(n, n, replace = TRUE)\n    sum(inc[idx]) / sum(prem[idx])\n  })\n}\n\nboot_df <- clean |>\n  filter(total_premium > 0) |>\n  group_by(year) |>\n  group_modify(~ tibble(loss_ratio = boot_one_year(.x, B))) |>\n  ungroup()\n\n\nboot_summary <- boot_df |>\n  group_by(year) |>\n  summarise(\n    lr_median = median(loss_ratio),\n    lr_lower = quantile(loss_ratio, 0.025),\n    lr_upper = quantile(loss_ratio, 0.975),\n    .groups = \"drop\"\n  )\n\nggplot(boot_df, aes(x = loss_ratio, y = factor(year))) +\n  stat_halfeye(aes(fill = factor(year)),\n               .width = c(.95), point_interval = \"mean_qi\",\n               alpha = 0.8, slab_colour = \"white\", slab_linewidth = 0.5) +\n  geom_vline(xintercept = 0.70, linetype = \"dashed\", colour = house_benchmark) +\n  annotate(\"text\", x = 0.70, y = 3.55, label = \"70% benchmark\",\n           hjust = 1.05, size = 3, colour = \"grey40\", fontface = \"italic\") +\n  annotate(\"curve\",\n           x = 0.78, xend = 0.745,\n           y = 3.2, yend = 3.1,\n           arrow = arrow(length = unit(2, \"mm\"), type = \"closed\"),\n           curvature = 0.3, colour = house_highlight, linewidth = 0.4) +\n  annotate(\"text\",\n           x = 0.79, y = 3.25,\n           label = \"2024 distribution sits\\nentirely above earlier years\",\n           hjust = 0, size = 3.2, colour = house_highlight, lineheight = 0.95) +\n  scale_x_continuous(labels = label_percent(accuracy = 1),\n                     limits = c(0.6, 0.85)) +\n  scale_fill_manual(values = c(\"2022\" = \"grey75\",\n                                \"2023\" = \"grey55\",\n                                \"2024\" = house_highlight),\n                    guide = \"none\") +\n  labs(\n    title = \"2024 loss ratio is well outside the prior-year range\",\n    subtitle = \"Bootstrap distribution of portfolio loss ratio by year (500 resamples)\",\n    x = \"Bootstrap loss ratio\",\n    y = NULL,\n    caption = \"Source: Spanish motor insurance portfolio (Mendeley Data).\"\n  ) +\n  theme_house(base_size = 11)\n```\n\n::: {.cell-output-display}\n![](TH_EX01_report_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\nThe 95% intervals for 2022 and 2023 overlap substantially, but the 2024 distribution sits entirely above both prior years. The intervals are well-separated and statistically distinct. The deterioration is a real shift, not sampling noise.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nyr_per_pol <- yr |>\n  mutate(\n    premium_per_pol = premium / n_pol,\n    incurred_per_pol = incurred / n_pol\n  ) |>\n  select(year, premium_per_pol, incurred_per_pol) |>\n  pivot_longer(c(premium_per_pol, incurred_per_pol),\n               names_to = \"metric\") |>\n  mutate(metric = factor(metric,\n                          levels = c(\"premium_per_pol\", \"incurred_per_pol\"),\n                          labels = c(\"Premium per policy (€)\",\n                                     \"Incurred losses per policy (€)\")))\n\nggplot(yr_per_pol, aes(x = year, y = value, colour = metric, group = metric)) +\n  geom_line(linewidth = 1.2) +\n  geom_point(size = 3.5) +\n  geom_text(aes(label = paste0(\"€\", round(value))),\n            vjust = -1.4, size = 3.2, fontface = \"bold\", show.legend = FALSE) +\n  scale_x_continuous(breaks = c(2022, 2023, 2024)) +\n  scale_y_continuous(expand = expansion(mult = c(0.1, 0.25))) +\n  scale_colour_manual(values = c(\"Premium per policy (€)\" = house_benchmark,\n                                  \"Incurred losses per policy (€)\" = house_highlight)) +\n  labs(\n    title = \"Incurred losses rose faster than premium across the period\",\n    subtitle = \"Per-policy economics, 2022–2024\",\n    x = \"Year\",\n    y = \"Euros per policy\",\n    colour = NULL,\n    caption = \"Source: Spanish motor insurance portfolio (Mendeley Data).\\nThe deterioration is decomposed in the following table.\"\n  ) +\n  theme_house(base_size = 11) +\n  theme(legend.position = \"top\")\n```\n\n::: {.cell-output-display}\n![](TH_EX01_report_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\nThe aggregate decomposition shows a clear gap: premium per policy rose from €278 in 2022 to €303 in 2024 (a 9 percent increase), while incurred losses per policy rose from €183 to €226 (a 24 percent increase). Average frequency and average severity remained nearly flat across the period (frequency 0.302 to 0.311, severity €969 to €971). The portfolio-level deterioration therefore did not arise from a uniform rise in claim incidence or claim size. Where the deterioration originates is not yet clear from the aggregate view. A decomposition follows.\n\nA standard within-versus-between decomposition isolates the source of the 8.9-percentage-point loss-ratio swing. The 2022 portfolio loss ratio is recomputed three ways: (i) with 2022 segment loss ratios and 2022 segment weights (the actual 2022 value), (ii) with 2024 segment loss ratios but 2022 segment weights (the within-segment effect: how much the deterioration would have been if mix had stayed constant), and (iii) with 2022 segment loss ratios but 2024 segment weights (the between-segment effect: how much the deterioration would have been if segments themselves hadn't moved). The residual is the interaction. Segments are defined by policy type, the dimension that dominated the bivariate findings.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseg_year <- clean |>\n  filter(total_premium > 0) |>\n  group_by(year, policy_type) |>\n  summarise(\n    premium = sum(total_premium),\n    incurred = sum(total_incurred),\n    lr = incurred / premium,\n    .groups = \"drop\"\n  ) |>\n  group_by(year) |>\n  mutate(weight = premium / sum(premium)) |>\n  ungroup()\n\nlr_2022 <- seg_year |> filter(year == 2022) |> select(policy_type, lr_2022 = lr, w_2022 = weight)\nlr_2024 <- seg_year |> filter(year == 2024) |> select(policy_type, lr_2024 = lr, w_2024 = weight)\n\ndecomp <- lr_2022 |>\n  full_join(lr_2024, by = \"policy_type\") |>\n  mutate(\n    contrib_within  = w_2022 * (lr_2024 - lr_2022),\n    contrib_between = lr_2022 * (w_2024 - w_2022),\n    contrib_interaction = (lr_2024 - lr_2022) * (w_2024 - w_2022)\n  )\n\ndecomp_summary <- tibble(\n  component = c(\"Actual 2022 → 2024 swing\",\n                \"Within-segment effect (segments worsened)\",\n                \"Between-segment effect (mix shifted)\",\n                \"Interaction\"),\n  value = c(\n    sum(decomp$lr_2024 * decomp$w_2024) - sum(decomp$lr_2022 * decomp$w_2022),\n    sum(decomp$contrib_within),\n    sum(decomp$contrib_between),\n    sum(decomp$contrib_interaction)\n  )\n)\n\ndecomp_summary |>\n  mutate(value = scales::percent(value, accuracy = 0.1)) |>\n  kable(caption = \"Decomposition of 2022 → 2024 portfolio loss-ratio swing\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Decomposition of 2022 → 2024 portfolio loss-ratio swing\n\n|component                                 |value |\n|:-----------------------------------------|:-----|\n|Actual 2022 → 2024 swing                  |8.9%  |\n|Within-segment effect (segments worsened) |8.5%  |\n|Between-segment effect (mix shifted)      |0.1%  |\n|Interaction                               |0.4%  |\n\n\n:::\n:::\n\n\nThe decomposition is unambiguous. The within-segment effect accounts for 8.5 of the 8.9-percentage-point swing, while the between-segment effect contributes only 0.1pp and the interaction 0.4pp. The portfolio's deterioration is therefore driven by segments themselves becoming less profitable over the period, not by a shift in business volume toward worse-performing segments. The book's policy-type composition was stable; what changed was the loss ratio within each existing segment. The bivariate analysis in the remainder of Section 4 identifies which specific segments deteriorated and where premium adequacy is most strained, beginning with the policy-type gradient in Section 4.3.\n\n\n## Coverage tier: the COMP_N premium-exposure mismatch\n\nThe portfolio is segmented into five coverage tiers by `policy_type`, ranging from basic third-party (TP) to comprehensive without excess (COMP_N). Loss-ratio variation across these tiers reveals whether premium charged is commensurate with the broader coverage offered.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npt <- clean |>\n  group_by(policy_type) |>\n  summarise(\n    n_pol      = n(),\n    premium    = sum(total_premium),\n    incurred   = sum(total_incurred),\n    exposure   = sum(total_exposure),\n    claims     = sum(total_claims),\n    loss_ratio = incurred / premium,\n    frequency  = claims / exposure,\n    severity   = if_else(claims > 0, incurred / claims, NA_real_),\n    .groups    = \"drop\"\n  )\n\npt |>\n  kable(\n    caption = \"Portfolio KPIs by policy type\",\n    digits = c(0, 0, 0, 0, 0, 0, 4, 4, 0),\n    format.args = list(big.mark = \",\")\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Portfolio KPIs by policy type\n\n|policy_type |   n_pol|    premium|   incurred| exposure| claims| loss_ratio| frequency| severity|\n|:-----------|-------:|----------:|----------:|--------:|------:|----------:|---------:|--------:|\n|TP          |   5,701|  1,009,417|    551,123|    3,768|    503|     0.5460|    0.1335|    1,096|\n|TPG         |  35,988|  8,106,186|  5,638,790|   24,656|  5,108|     0.6956|    0.2072|    1,104|\n|CC          | 204,318| 49,715,172| 31,545,729|  144,010| 31,800|     0.6345|    0.2208|      992|\n|COMP_E      |  90,320| 35,335,541| 26,128,628|   64,417| 26,382|     0.7394|    0.4095|      990|\n|COMP_N      |  16,013| 10,213,966|  9,547,811|   12,221| 12,751|     0.9348|    1.0433|      749|\n\n\n:::\n:::\n\n\nThe numbers reveal a monotonic gradient. Basic third-party (TP) policies run a loss ratio of around 54%, well inside profitable territory. Loss ratio rises through TPG and CC, reaches the mid-70s for COMP_E, and arrives at COMP_N at approximately 93.5%. The COMP_N segment is within touching distance of pure-loss breakeven before any expense loading is applied.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npt_plot_data <- pt |>\n  mutate(\n    highlight = if_else(policy_type == \"COMP_N\", \"COMP_N\", \"Other tiers\"),\n    label_text = percent(loss_ratio, accuracy = 0.1)\n  )\n\nggplot(pt_plot_data, aes(x = policy_type, y = loss_ratio, fill = highlight)) +\n  geom_col(width = 0.7) +\n  geom_hline(yintercept = 0.70, linetype = \"dashed\", colour = \"grey40\") +\n  geom_text(aes(label = label_text,\n                colour = highlight),\n            vjust = -0.6, size = 3.6, fontface = \"bold\") +\n  geom_text(aes(label = paste0(\"n = \", comma(n_pol)), y = 0.02),\n            colour = \"white\", size = 2.8, vjust = 0) +\n  annotate(\"text\",\n           x = 0.6, y = 0.72,\n           label = \"70% benchmark\",\n           hjust = 0, size = 3, colour = \"grey40\", fontface = \"italic\") +\n  annotate(\"curve\",\n          x = 4.3, xend = 4.85,\n          y = 0.82, yend = 0.92,\n          arrow = arrow(length = unit(2.5, \"mm\"), type = \"closed\"),\n          curvature = -0.3, colour = \"#C44E52\", linewidth = 0.6) +\n  annotate(\"text\",\n           x = 4.2, y = 0.84,\n           label = \"COMP_N runs 23.5 points\\nabove the benchmark\",\n           hjust = 1, size = 3.2, colour = \"#C44E52\", lineheight = 0.95) +\n  scale_y_continuous(labels = label_percent(accuracy = 1),\n                     limits = c(0, 1.05),\n                     expand = expansion(mult = c(0, 0.05))) +\n  scale_fill_manual(values = c(\"COMP_N\" = \"#C44E52\",\n                                \"Other tiers\" = \"grey75\"),\n                    guide = \"none\") +\n  scale_colour_manual(values = c(\"COMP_N\" = \"#C44E52\",\n                                  \"Other tiers\" = \"grey40\"),\n                      guide = \"none\") +\n  labs(\n    title = \"Comprehensive-without-excess runs at 93.5% loss ratio\",\n    subtitle = \"Loss ratio across five coverage tiers, 2022–2024 portfolio\",\n    x = \"Policy type (ordered from least to most comprehensive)\",\n    y = \"Loss ratio\",\n    caption = \"Source: Spanish motor insurance portfolio (Mendeley Data).\"\n  ) +\n  theme_minimal(base_size = 11) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 13),\n    plot.subtitle = element_text(colour = \"grey40\", size = 10, margin = margin(b = 10)),\n    plot.caption = element_text(colour = \"grey50\", size = 8, hjust = 0),\n    panel.grid.major.x = element_blank(),\n    panel.grid.minor = element_blank(),\n    axis.text = element_text(size = 9),\n    axis.title = element_text(size = 9.5)\n  )\n```\n\n::: {.cell-output-display}\n![](TH_EX01_report_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n\nTo validate that the policy-type differences reflect underlying segment behaviour rather than artefacts of skewed within-segment distributions, a non-parametric test is applied to the policy-level loss ratio (filtered to policies with claims, where the metric is informative).\n\nBefore the formal test, a ridgeline view of the policy-level loss-ratio distributions makes the within-segment shape visible across all five tiers at once.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclean |>\n  filter(total_claims > 0, is.finite(loss_ratio),\n         loss_ratio >= 0.01, loss_ratio <= 100) |>\n  ggplot(aes(x = loss_ratio,\n             y = fct_rev(policy_type),\n             fill = policy_type)) +\n  geom_density_ridges(scale = 1.4, alpha = 0.85,\n                      colour = \"white\", linewidth = 0.4,\n                      quantile_lines = TRUE, quantiles = 2) +\n  geom_vline(xintercept = 1,\n             linetype = \"dashed\", colour = house_benchmark) +\n  annotate(\"text\", x = 1.05, y = 5.6,\n           label = \"Break-even (100%)\",\n           hjust = 0, size = 3, colour = house_benchmark,\n           fontface = \"italic\") +\n  scale_x_continuous(trans = \"log10\",\n                     breaks = c(0.01, 0.1, 1, 10, 100),\n                     labels = c(\"1%\", \"10%\", \"100%\", \"1,000%\", \"10,000%\")) +\n  scale_fill_manual(values = c(\"TP\"     = \"grey75\",\n                                \"TPG\"    = \"grey75\",\n                                \"CC\"     = \"grey75\",\n                                \"COMP_E\" = \"grey75\",\n                                \"COMP_N\" = house_highlight),\n                    guide = \"none\") +\n  labs(\n    title = \"COMP_N's loss-ratio distribution sits visibly to the right of every other tier\",\n    subtitle = \"Ridgeline densities of policy-level loss ratio across five coverage tiers (claims-positive policies, log scale)\",\n    x = \"Loss ratio (log scale)\",\n    y = NULL,\n    caption = \"Source: Spanish motor insurance portfolio (Mendeley Data).\\nWhite vertical lines mark the within-tier median.\"\n  ) +\n  theme_house(base_size = 11) +\n  theme(panel.grid.major.y = element_blank(),\n        plot.margin = margin(t = 25, r = 15, b = 15, l = 10))\n```\n\n::: {.cell-output-display}\n![](TH_EX01_report_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclean |>\n  filter(total_claims > 0,\n         is.finite(loss_ratio),\n         loss_ratio >= 0.05, loss_ratio <= 50) |>\n  ggbetweenstats(\n    x = policy_type,\n    y = loss_ratio,\n    type = \"np\",\n    pairwise.display = \"significant\",\n    p.adjust.method = \"fdr\",\n    plot.type = \"boxviolin\",\n    centrality.plotting = TRUE,\n    bf.message = FALSE,\n    ggtheme = theme_minimal()\n  ) +\n  scale_colour_manual(values = c(\"TP\" = \"grey60\",\n                                  \"TPG\" = \"grey60\",\n                                  \"CC\" = \"grey60\",\n                                  \"COMP_E\" = \"grey60\",\n                                  \"COMP_N\" = house_highlight),\n                      guide = \"none\") +\n  scale_fill_manual(values = c(\"TP\" = \"grey60\",\n                                \"TPG\" = \"grey60\",\n                                \"CC\" = \"grey60\",\n                                \"COMP_E\" = \"grey60\",\n                                \"COMP_N\" = house_highlight),\n                    guide = \"none\") +\n  scale_y_continuous(\n    trans  = \"log10\",\n    breaks = c(0.1, 0.5, 1, 5, 20),\n    labels = c(\"10%\", \"50%\", \"100%\", \"500%\", \"2,000%\")\n  ) +\n  coord_cartesian(ylim = c(0.05, 50)) +\n  labs(x = \"Policy type\",\n       y = \"Policy-level loss ratio (log scale, claims-positive only)\")\n```\n\n::: {.cell-output-display}\n![](TH_EX01_report_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n\nThe Kruskal-Wallis test on policy-level loss ratio rejects the null of equal distributions across policy types at any conventional significance level. Pairwise comparisons (FDR-adjusted) confirm that COMP_N is significantly different from every other tier. The finding represents a systematic pricing inadequacy rather than statistical noise.\n\nThe diagnosis is that comprehensive-without-excess is sold at premium levels that do not reflect its actual loss exposure. Swiss Re's framework describes this pattern as a premium and exposure mismatch.\n\n\n## The bonus-malus paradox\n\n`bonus_score` is the insurer's primary mechanism for adjusting premium to historical claim behaviour. Three categories are used: Good (no recent claims), Neutral (intermediate), and Bad (recent claims history). The expectation is straightforward. Claim frequency should rise from Good to Bad, and loss ratio should follow, unless the pricing applied to Bad policies has already absorbed their elevated frequency.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbs <- clean |>\n  group_by(bonus_score) |>\n  summarise(\n    n_pol      = n(),\n    premium    = sum(total_premium),\n    incurred   = sum(total_incurred),\n    exposure   = sum(total_exposure),\n    claims     = sum(total_claims),\n    loss_ratio = incurred / premium,\n    frequency  = claims / exposure,\n    severity   = if_else(claims > 0, incurred / claims, NA_real_),\n    avg_prem   = premium / exposure,\n    .groups    = \"drop\"\n  )\n\nbs |>\n  kable(\n    caption = \"Portfolio KPIs by bonus-malus category\",\n    digits = c(0, 0, 0, 0, 0, 0, 4, 4, 0, 0),\n    format.args = list(big.mark = \",\")\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Portfolio KPIs by bonus-malus category\n\n|bonus_score |   n_pol|    premium|   incurred| exposure| claims| loss_ratio| frequency| severity| avg_prem|\n|:-----------|-------:|----------:|----------:|--------:|------:|----------:|---------:|--------:|--------:|\n|Good        | 339,838| 98,394,834| 68,575,327|  241,164| 72,324|     0.6969|    0.2999|      948|      408|\n|Neutral     |   7,809|  3,241,604|  2,653,555|    4,855|  2,321|     0.8186|    0.4781|    1,143|      668|\n|Bad         |   4,693|  2,743,843|  2,183,200|    3,053|  1,899|     0.7957|    0.6219|    1,150|      899|\n\n\n:::\n:::\n\n\nThe frequency column behaves as expected: 0.30 for Good, 0.48 for Neutral, 0.62 for Bad, a clean monotonic rise. Premium per exposure also rises monotonically, as the bonus-malus surcharges intend. The loss ratio tells a different story.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbs_se <- clean |>\n  group_by(bonus_score) |>\n  summarise(\n    n_pol      = n(),\n    incurred   = sum(total_incurred),\n    premium    = sum(total_premium),\n    exposure   = sum(total_exposure),\n    claims     = sum(total_claims),\n    loss_ratio = incurred / premium,\n    lr_se      = sqrt((incurred / premium) * (1 - incurred / premium) / premium),\n    lr_lower   = pmax(0, loss_ratio - 1.96 * lr_se),\n    lr_upper   = loss_ratio + 1.96 * lr_se,\n    frequency  = claims / exposure,\n    freq_se    = sqrt(claims) / exposure,\n    freq_lower = pmax(0, frequency - 1.96 * freq_se),\n    freq_upper = frequency + 1.96 * freq_se,\n    avg_prem   = premium / exposure,\n    .groups    = \"drop\"\n  ) |>\n  mutate(highlight = if_else(bonus_score == \"Neutral\", \"Neutral\", \"Other\"))\n\npanel_style <- list(\n  scale_colour_manual(values = c(\"Neutral\" = house_highlight,\n                                  \"Other\" = house_benchmark),\n                      guide = \"none\"),\n  theme_house(base_size = 10),\n  theme(plot.subtitle = element_text(face = \"bold\", colour = \"grey20\",\n                                     size = 10, margin = margin(b = 5)))\n)\n\np_lr <- ggplot(bs_se, aes(x = bonus_score, y = loss_ratio, colour = highlight)) +\n  geom_errorbar(aes(ymin = lr_lower, ymax = lr_upper), width = 0.15, linewidth = 0.6) +\n  geom_point(size = 4) +\n  geom_text(aes(label = percent(loss_ratio, accuracy = 0.1)),\n            vjust = -1.6, size = 3.3, fontface = \"bold\") +\n  scale_y_continuous(labels = label_percent(accuracy = 1),\n                     expand = expansion(mult = c(0.15, 0.45))) +\n  labs(x = NULL, y = \"Loss ratio\", subtitle = \"Loss ratio (with 95% CI)\") +\n  panel_style\n\np_freq <- ggplot(bs_se, aes(x = bonus_score, y = frequency, colour = highlight)) +\n  geom_errorbar(aes(ymin = freq_lower, ymax = freq_upper), width = 0.15, linewidth = 0.6) +\n  geom_point(size = 4) +\n  geom_text(aes(label = round(frequency, 3)),\n            vjust = -1.6, size = 3.3, fontface = \"bold\") +\n  scale_y_continuous(expand = expansion(mult = c(0.15, 0.45))) +\n  labs(x = NULL, y = \"Frequency\", subtitle = \"Claim frequency (claims per policy-year)\") +\n  panel_style\n\np_prem <- ggplot(bs_se, aes(x = bonus_score, y = avg_prem, colour = highlight)) +\n  geom_point(size = 4) +\n  geom_text(aes(label = paste0(\"€\", round(avg_prem))),\n            vjust = -1.6, size = 3.3, fontface = \"bold\") +\n  scale_y_continuous(expand = expansion(mult = c(0.15, 0.45))) +\n  labs(x = \"Bonus-malus category\", y = \"Premium / exposure (€)\",\n       subtitle = \"Average premium per unit of exposure\") +\n  panel_style\n\n(p_lr / p_freq / p_prem) +\n  plot_annotation(\n    title = \"Neutral pays less but loses more: the bonus-malus paradox\",\n    subtitle = \"Loss ratio, frequency, and premium per exposure by bonus-malus category, 2022–2024\",\n    caption = \"Source: Spanish motor insurance portfolio (Mendeley Data). \\n95% confidence intervals from binomial (loss ratio) and Poisson (frequency) approximations.\",\n    theme = theme(\n      plot.title = element_text(face = \"bold\", size = 13),\n      plot.subtitle = element_text(colour = \"grey40\", size = 10, margin = margin(b = 12)),\n      plot.caption = element_text(colour = \"grey50\", size = 8, hjust = 0)\n    )\n  )\n```\n\n::: {.cell-output-display}\n![](TH_EX01_report_files/figure-html/unnamed-chunk-39-1.png){width=672}\n:::\n:::\n\n\nThe three-panel composite makes the paradox visible. Frequency rises monotonically across Good, Neutral, and Bad (0.30, 0.48, 0.62 claims per policy-year), and average premium per exposure does the same (€408, €668, €899). Loss ratio does not follow that pattern. Neutral runs at 81.9 percent, materially above the 79.6 percent of Bad, despite collecting 26 percent less premium per exposure. The 95% confidence intervals on loss ratio and frequency confirm that the gap is not noise. The bonus-malus mechanism is absorbing the elevated frequency in the Bad tier but not in Neutral.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclean |>\n  filter(total_claims > 0,\n         is.finite(loss_ratio),\n         loss_ratio >= 0.05, loss_ratio <= 50) |>\n  ggbetweenstats(\n    x = bonus_score,\n    y = loss_ratio,\n    type = \"np\",\n    pairwise.display = \"significant\",\n    p.adjust.method = \"fdr\",\n    plot.type = \"boxviolin\",\n    bf.message = FALSE,\n    ggtheme = theme_minimal()\n  ) +\n  scale_colour_manual(values = c(\"Good\" = \"grey60\",\n                                  \"Neutral\" = house_highlight,\n                                  \"Bad\" = \"grey60\"),\n                      guide = \"none\") +\n  scale_fill_manual(values = c(\"Good\" = \"grey60\",\n                                \"Neutral\" = house_highlight,\n                                \"Bad\" = \"grey60\"),\n                    guide = \"none\") +\n  scale_y_continuous(\n    trans  = \"log10\",\n    breaks = c(0.1, 0.5, 1, 5, 20),\n    labels = c(\"10%\", \"50%\", \"100%\", \"500%\", \"2,000%\")\n  ) +\n  coord_cartesian(ylim = c(0.05, 50)) +\n  labs(x = \"Bonus-malus category\",\n       y = \"Policy-level loss ratio (log scale, claims-positive only)\")\n```\n\n::: {.cell-output-display}\n![](TH_EX01_report_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\n\nThe chart shows policy-level loss ratio among claims-positive policies, which inverts the directional pattern of the segment-level aggregate above. Good-tier policies have the lowest premium, so a single claim produces a high policy-level ratio; the segment-level view is dominated instead by the much larger share of zero-claim policies. The statistical test confirms that the Neutral and Bad distributions differ, and that Good is materially separated from both. The Neutral segment is the pricing gap. Two non-exclusive explanations are plausible:\n\n1.  **New entrants land in Neutral by default**, before sufficient claim history has accumulated to move them up or down, and the default premium does not load adequately for the embedded risk in this group.\n2.  **Bonus-malus transitions are downward-rigid**: a policyholder who claims may stay in Neutral rather than move to Bad, again undercharging for actual loss potential.\n\nSection 5 (panel transition analysis) examines the second hypothesis directly by tracking individual policyholders across years.\n\n## Geographic interaction: where losses concentrate\n\nThe portfolio is described by two geographic variables. `municipality_type` distinguishes interior, coastal, and island regions. `circulation_area` classifies the policy's primary driving environment as urban or rural. Examined in isolation, neither variable produces a dramatic loss-ratio gradient. Their interaction does.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngeo <- clean |>\n  group_by(municipality_type, circulation_area) |>\n  summarise(\n    n_pol      = n(),\n    premium    = sum(total_premium),\n    incurred   = sum(total_incurred),\n    exposure   = sum(total_exposure),\n    claims     = sum(total_claims),\n    loss_ratio = incurred / premium,\n    frequency  = claims / exposure,\n    .groups    = \"drop\"\n  )\n\ngeo |>\n  kable(\n    caption = \"Portfolio KPIs by municipality type and circulation area\",\n    digits = c(0, 0, 0, 0, 0, 0, 0, 4, 4),\n    format.args = list(big.mark = \",\")\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Portfolio KPIs by municipality type and circulation area\n\n|municipality_type |circulation_area |   n_pol|    premium|   incurred| exposure| claims| loss_ratio| frequency|\n|:-----------------|:----------------|-------:|----------:|----------:|--------:|------:|----------:|---------:|\n|Interior          |Urban            | 112,349| 35,698,870| 25,614,951|   79,889| 28,880|     0.7175|    0.3615|\n|Interior          |Rural            | 115,276| 32,281,521| 21,923,212|   80,459| 22,829|     0.6791|    0.2837|\n|Coastal           |Urban            |  66,562| 20,226,486| 14,168,191|   47,271| 14,090|     0.7005|    0.2981|\n|Coastal           |Rural            |  34,194|  9,945,797|  7,282,972|   24,205|  6,414|     0.7323|    0.2650|\n|Islands           |Urban            |  10,568|  2,852,709|  2,202,529|    7,574|  2,046|     0.7721|    0.2701|\n|Islands           |Rural            |  13,391|  3,374,899|  2,220,226|    9,675|  2,285|     0.6579|    0.2362|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngeo_segment <- clean |>\n  group_by(municipality_type, circulation_area) |>\n  summarise(\n    n_pol = n(),\n    premium = sum(total_premium),\n    incurred = sum(total_incurred),\n    loss_ratio = incurred / premium,\n    .groups = \"drop\"\n  ) |>\n  mutate(\n    is_outlier = municipality_type == \"Islands\" & circulation_area == \"Urban\"\n  )\n\nggplot(geo_segment,\n       aes(x = circulation_area, y = municipality_type, fill = loss_ratio)) +\n  geom_tile(colour = \"white\", linewidth = 1.5) +\n  geom_text(aes(label = paste0(percent(loss_ratio, accuracy = 0.1),\n                                \"\\nn = \", comma(n_pol)),\n                fontface = if_else(is_outlier, \"bold\", \"plain\")),\n            size = 3.4, lineheight = 0.95,\n            colour = \"grey20\") +\n    scale_fill_distiller(palette = house_sequential, direction = -1,\n                       labels = label_percent(accuracy = 1),\n                       name = \"Loss ratio\") +\n  scale_x_discrete(expand = c(0, 0)) +\n  scale_y_discrete(expand = c(0, 0)) +\n  coord_cartesian(clip = \"off\", ylim = c(0.5, 3.5)) +\n  labs(\n    title = \"Urban island policies run 11 points above rural island policies\",\n    subtitle = \"Loss ratio by circulation area and municipality type\",\n    x = \"Circulation area\",\n    y = \"Municipality type\",\n    caption = \"Source: Spanish motor insurance portfolio (Mendeley Data).\\nCell labels show loss ratio and number of policies.\"\n  ) +\n  theme_house(base_size = 11) +\n  theme(\n    panel.grid = element_blank(),\n    legend.position = \"right\",\n    plot.margin = margin(t = 35, r = 15, b = 15, l = 50)\n  )\n```\n\n::: {.cell-output-display}\n![](TH_EX01_report_files/figure-html/unnamed-chunk-42-1.png){width=672}\n:::\n:::\n\n\nThe heatmap shows the interaction at a glance. Interior regions are uniform across urban and rural. Coastal urban runs slightly higher than coastal rural. The islands show the widest within-category spread: rural island policies are the most profitable segment in the portfolio at around 65% loss ratio, while urban island policies sit at around 77%. An 11-percentage-point spread within a single municipality category points to a real underwriting gap.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclean |>\n  mutate(\n    claims_bin = if_else(total_claims > 0, \"Claim\", \"No claim\"),\n    geo_segment = case_when(\n      municipality_type == \"Interior\" & circulation_area == \"Rural\" ~ \"Int·Rur\",\n      municipality_type == \"Interior\" & circulation_area == \"Urban\" ~ \"Int·Urb\",\n      municipality_type == \"Coastal\"  & circulation_area == \"Rural\" ~ \"Coa·Rur\",\n      municipality_type == \"Coastal\"  & circulation_area == \"Urban\" ~ \"Coa·Urb\",\n      municipality_type == \"Islands\"  & circulation_area == \"Rural\" ~ \"Isl·Rur\",\n      municipality_type == \"Islands\"  & circulation_area == \"Urban\" ~ \"Isl·Urb\"\n    ),\n    geo_segment = factor(geo_segment,\n                         levels = c(\"Coa·Rur\",\"Coa·Urb\",\"Int·Rur\",\n                                    \"Int·Urb\",\"Isl·Rur\",\"Isl·Urb\"))\n  ) |>\n  ggbarstats(\n    x = claims_bin,\n    y = geo_segment,\n    label = \"percentage\",\n    bf.message = FALSE,\n    ggtheme = theme_minimal()\n  ) +\n  scale_fill_manual(values = c(\"Claim\" = house_highlight,\n                                \"No claim\" = house_muted)) +\n  labs(x = \"Geographic segment  (Int = Interior, Coa = Coastal, Isl = Islands)\",\n       y = \"Share of policies\")\n```\n\n::: {.cell-output-display}\n![](TH_EX01_report_files/figure-html/unnamed-chunk-43-1.png){width=960}\n:::\n:::\n\n\nA chi-square test of independence on the claim-versus-no-claim binary across the six geographic segments rejects the null of independence. The effect size (Cramér's V) is small in absolute terms, which is expected when most policies have no claims, but the differences across segments are statistically robust given the sample size.\n\nThe 11-point spread within the islands category indicates that aggregate municipality-level summaries mask underlying within-region heterogeneity.\n\n\n## Driver age and vehicle age: a risk surface\n\nDriver age and vehicle age are continuous variables. Examining them jointly via the loss-ratio surface reveals which combinations carry the highest expected losses, beyond what either variable alone would suggest.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nage_interaction <- clean |>\n  group_by(driver_age_band, vehicle_age_band) |>\n  summarise(\n    n_pol = n(),\n    premium = sum(total_premium),\n    incurred = sum(total_incurred),\n    loss_ratio = incurred / premium,\n    .groups = \"drop\"\n  ) |>\n  filter(n_pol >= 500)\n\nworst_cell <- age_interaction |>\n  slice_max(loss_ratio, n = 1)\n\nggplot(age_interaction,\n       aes(x = driver_age_band, y = vehicle_age_band, fill = loss_ratio)) +\n  geom_tile(colour = \"white\", linewidth = 1.5) +\n  geom_tile(data = worst_cell,\n            colour = \"grey15\", linewidth = 1.8, fill = NA) +\n  geom_text(aes(label = paste0(percent(loss_ratio, accuracy = 0.1),\n                                \"\\nn = \", comma(n_pol))),\n            size = 3, lineheight = 0.95, colour = \"grey20\") +\n  scale_fill_distiller(palette = house_sequential, direction = -1,\n                       labels = label_percent(accuracy = 1),\n                       name = \"Loss ratio\") +\n  scale_x_discrete(expand = c(0, 0)) +\n  scale_y_discrete(expand = c(0, 0)) +\n  labs(\n    title = \"Young drivers in older vehicles carry the highest loss ratios\",\n    subtitle = \"Loss ratio by driver age band and vehicle age band; cells with fewer than 500 policies suppressed\",\n    x = \"Driver age band\",\n    y = \"Vehicle age band\",\n    caption = \"Source: Spanish motor insurance portfolio (Mendeley Data).\\nCell labels show loss ratio and policy count; the worst cell is outlined.\"\n  ) +\n  theme_house(base_size = 11) +\n  theme(panel.grid = element_blank())\n```\n\n::: {.cell-output-display}\n![](TH_EX01_report_files/figure-html/unnamed-chunk-44-1.png){width=672}\n:::\n:::\n\nThe banded heatmap makes the interaction structure explicit. The under-25 driver band paired with vehicle ages 11 and above shows the highest loss ratios in the surface. The 25 to 49 driver bands show flatter loss-ratio profiles across vehicle ages, indicating that the interaction effect is concentrated in the youngest driver segment. The 65+ band shows a mild upward drift in newer vehicles, consistent with senior drivers in higher-value vehicles carrying distinct loss profiles.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclean |>\n  filter(total_claims > 0,\n         is.finite(loss_ratio),\n         loss_ratio >= 0.05, loss_ratio <= 50) |>\n  ggbetweenstats(\n    x = driver_age_band,\n    y = loss_ratio,\n    type = \"np\",\n    pairwise.display = \"significant\",\n    p.adjust.method = \"fdr\",\n    plot.type = \"boxviolin\",\n    bf.message = FALSE,\n    ggtheme = theme_minimal()\n  ) +\n  scale_colour_manual(values = c(\"<25\" = house_highlight,\n                                  \"25-34\" = \"grey60\",\n                                  \"35-49\" = \"grey60\",\n                                  \"50-64\" = \"grey60\",\n                                  \"65+\" = \"grey60\"),\n                      guide = \"none\") +\n  scale_fill_manual(values = c(\"<25\" = house_highlight,\n                                \"25-34\" = \"grey60\",\n                                \"35-49\" = \"grey60\",\n                                \"50-64\" = \"grey60\",\n                                \"65+\" = \"grey60\"),\n                    guide = \"none\") +\n  scale_y_continuous(\n    trans  = \"log10\",\n    breaks = c(0.1, 0.5, 1, 5, 20),\n    labels = c(\"10%\", \"50%\", \"100%\", \"500%\", \"2,000%\")\n  ) +\n  coord_cartesian(ylim = c(0.05, 50)) +\n  labs(x = \"Driver age band\",\n       y = \"Policy-level loss ratio (log scale, claims-positive only)\")\n```\n\n::: {.cell-output-display}\n![](TH_EX01_report_files/figure-html/unnamed-chunk-45-1.png){width=672}\n:::\n:::\n\n\nThe Kruskal-Wallis test across driver-age bands rejects the equality null. Pairwise comparisons identify the under-25 segment as significantly different from the 35-49 and 50-64 bands. Both age extremes carry elevated within-segment loss variance, consistent with the wider risk distributions characteristic of younger and older drivers.\n\n## Volatility view\n\nProfitability and volatility are conceptually distinct. A segment can have a low mean loss ratio with high variance, making it unpredictable even if it averages out acceptably. The coefficient of variation of policy-level loss ratio captures this directly.\n\nPolicies with non-finite loss ratios (caused by zero or missing premium values) are removed before computing volatility, to avoid distortion from undefined ratios.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrvol <- clean |>\n  filter(total_claims > 0,\n         is.finite(loss_ratio),\n         !is.na(loss_ratio)) |>\n  group_by(policy_type) |>\n  summarise(\n    n_pol = n(),\n    sd_lr = sd(loss_ratio, na.rm = TRUE),\n    .groups = \"drop\"\n  )\n\nvol <- pt |>\n  select(policy_type, n_pol, loss_ratio) |>\n  rename(segment_lr = loss_ratio) |>\n  left_join(rvol |> select(policy_type, sd_lr), by = \"policy_type\") |>\n  mutate(cv_lr = sd_lr / segment_lr)\n\nvol |>\n  kable(\n    caption = \"Segment-level loss ratio and within-segment volatility\",\n    digits = c(0, 0, 4, 3, 3),\n    format.args = list(big.mark = \",\")\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Segment-level loss ratio and within-segment volatility\n\n|policy_type |   n_pol| segment_lr|  sd_lr|   cv_lr|\n|:-----------|-------:|----------:|------:|-------:|\n|TP          |   5,701|     0.5460| 34.929|  63.974|\n|TPG         |  35,988|     0.6956| 52.489|  75.457|\n|CC          | 204,318|     0.6345| 34.395|  54.206|\n|COMP_E      |  90,320|     0.7394| 90.991| 123.054|\n|COMP_N      |  16,013|     0.9348|  7.119|   7.615|\n\n\n:::\n:::\n\n\nThe coefficient of variation here is defined as the policy-level standard deviation of loss ratio (among claims-positive policies) divided by the segment-level loss ratio. The numerator captures the within-segment dispersion an underwriter would face when pricing an individual policy in that segment; the denominator captures the segment's exposure-weighted central tendency. The two are computed at different levels of aggregation by design. A purely policy-level CV would weight each policy equally regardless of premium, while a purely segment-level CV (e.g., via bootstrap) would describe the segment-mean estimator's uncertainty rather than the within-segment dispersion across policies. The chosen definition prioritises the underwriter's perspective on individual-policy variance.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvol <- vol |>\n  mutate(highlight = if_else(policy_type == \"COMP_N\", \"COMP_N\", \"Other\"))\n\nggplot(vol, aes(x = segment_lr, y = cv_lr)) +\n  geom_hline(yintercept = mean(vol$cv_lr),\n             linetype = \"dashed\", colour = house_benchmark) +\n  geom_vline(xintercept = 0.70,\n             linetype = \"dashed\", colour = house_benchmark) +\n  geom_point(aes(size = n_pol, colour = highlight), alpha = 0.85) +\n  ggrepel::geom_text_repel(aes(label = policy_type, colour = highlight),\n                           size = 3.8, fontface = \"bold\",\n                           point.padding = 0.8, box.padding = 0.6,\n                           min.segment.length = 0, seed = 1,\n                           show.legend = FALSE) +\n  annotate(\"text\", x = 0.71, y = 5,\n           label = \"70% benchmark\", hjust = 0, size = 3,\n           colour = house_benchmark, fontface = \"italic\") +\n  annotate(\"text\", x = 0.52, y = mean(vol$cv_lr) + 4,\n           label = \"Portfolio mean CV\", hjust = 0, size = 3,\n           colour = house_benchmark, fontface = \"italic\") +\n  scale_x_continuous(labels = label_percent(accuracy = 1),\n                     limits = c(0.5, 1.0)) +\n  scale_y_continuous(limits = c(0, 140),\n                     expand = expansion(mult = c(0, 0.05))) +\n  scale_size(range = c(4, 14), guide = \"none\") +\n  scale_colour_manual(values = c(\"COMP_N\" = house_highlight,\n                                  \"Other\" = house_benchmark),\n                      guide = \"none\") +\n  labs(\n    title = \"COMP_N is the worst-performing tier but the most predictable\",\n    subtitle = \"Segment loss ratio versus within-segment volatility, bubble area proportional to policy count\",\n    x = \"Segment loss ratio (profitability axis)\",\n    y = \"Coefficient of variation (volatility axis)\",\n    caption = \"Source: Spanish motor insurance portfolio (Mendeley Data).\\nBubble size: number of policies in segment. Reference lines: 70% loss-ratio benchmark and portfolio-mean CV.\"\n  ) +\n  theme_house(base_size = 11)\n```\n\n::: {.cell-output-display}\n![](TH_EX01_report_files/figure-html/unnamed-chunk-47-1.png){width=672}\n:::\n:::\n\n\n\nThe two-axis view separates profitability from predictability. COMP_N has the worst segment loss ratio at 93.5% but the lowest within-segment volatility (CV 7.6), meaning its loss experience is unprofitable but highly predictable. COMP_E shows the opposite profile: a moderately high mean loss ratio of 73.9% paired with the highest volatility in the portfolio (CV 123), driven by occasional large-severity claims that dominate the segment's variance. CC combines a moderate segment loss ratio of 63.5% with mid-range volatility, the most balanced profile in the book.\n\nThese two segments illustrate that profitability and predictability operate on independent dimensions. COMP_N is unprofitable but predictable, while COMP_E is closer to break-even on average and its tail risk dominates the within-segment variance.\n\n\n## Section summary\n\nThe bivariate analysis identifies four loss drivers:\n\n1.  **Temporal deterioration**. The 2022 to 2024 loss-ratio trajectory shows a statistically validated worsening, with severity contributing more than frequency.\n2.  **Coverage tier mispricing**. COMP_N runs a loss ratio of 93.5%, materially worse than every other tier and statistically distinct in pairwise testing.\n3.  **Bonus-malus paradox**. The Neutral category carries the highest loss ratio in the portfolio despite middle-of-the-road claim frequency, suggesting either default-tier under-loading or downward-rigid bonus-malus transitions. Section 5 examines the transition dynamics directly.\n4.  **Geographic and age-driven concentration**. Urban island policies and young-driver-old-vehicle combinations both show elevated loss intensity, with the latter representing a joint pattern that additive treatment of the two age dimensions would miss.\n\n# Beyond standard techniques\n\nThe methods applied so far are drawn from the visual analytics curriculum covered in Lessons 1 through 5. This section adds three methods that sit outside that curriculum, selected because they leverage structural features of the data the standard techniques cannot reach. The first method visualises how policyholders move between bonus-malus categories over time, using the dataset's panel structure. The second method shows how unevenly losses are distributed across the policy population, using a concentration metric borrowed from actuarial practice. The third method groups segments by their multi-metric risk profile using hierarchical clustering, surfacing structural similarities that single-variable views cannot reveal.\n\n## Bonus-malus transitions over time\n\nThe same policyholder can appear in 2022, 2023, and 2024 records. This creates a panel structure that single-year cross-sectional analysis discards. The bonus-malus paradox identified in Section 4 (Neutral carrying higher loss ratio than Bad) raised the question of whether bonus-score transitions are downward-rigid. A Sankey diagram of category transitions answers this directly.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrans_22_24 <- clean |>\n  select(insured_id, year, bonus_score) |>\n  pivot_wider(names_from = year, values_from = bonus_score,\n              names_prefix = \"y\") |>\n  filter(!is.na(y2022), !is.na(y2024)) |>\n  filter(!(y2022 == \"Good\" & y2024 == \"Good\")) |>\n  count(y2022, y2024, name = \"policies\") |>\n  mutate(across(starts_with(\"y\"), ~ factor(.x, levels = c(\"Good\",\"Neutral\",\"Bad\"))))\n\nggplot(trans_22_24,\n       aes(axis1 = y2022, axis2 = y2024, y = policies)) +\n  geom_alluvium(aes(fill = y2022), alpha = 0.75, width = 0.3,\n                colour = \"white\", linewidth = 0.2) +\n  geom_stratum(width = 0.3, fill = \"grey90\", colour = \"grey50\") +\n  geom_text(stat = \"stratum\", aes(label = after_stat(stratum)),\n            size = 3.6, fontface = \"bold\") +\n  scale_x_discrete(limits = c(\"2022\", \"2024\"), expand = c(0.1, 0.1)) +\n  scale_fill_manual(values = c(\"Good\" = \"#4C72B0\",\n                                \"Neutral\" = \"#DDB237\",\n                                \"Bad\" = \"#C44E52\"),\n                    name = \"2022 starting category\") +\n  scale_y_continuous(labels = comma) +\n  labs(\n    title = \"Recovery dominates: most non-Good policyholders improved by 2024\",\n    subtitle = \"Bonus-malus transitions 2022 to 2024 (stable-Good policyholders excluded)\",\n    x = NULL,\n    y = \"Policyholders\",\n    caption = \"Source: Spanish motor insurance portfolio (Mendeley Data).\\nPolicyholders observed in both 2022 and 2024; stable-Good excluded.\"\n  ) +\n  theme_house(base_size = 11) +\n  theme(legend.position = \"top\")\n```\n\n::: {.cell-output-display}\n![](TH_EX01_report_files/figure-html/unnamed-chunk-48-1.png){width=672}\n:::\n:::\n\n\nThe Sankey reveals the structure of bonus-malus dynamics among policyholders whose category changed at least once between 2022 and 2024. (Policyholders who remained Good throughout, the largest single group at around 99 percent of the panel, are excluded to surface the transition dynamics.) Among the remaining policyholders, upward movement dominates: most who started in Neutral improved to Good, and most who started in Bad improved to Neutral or Good. A smaller but visible flow shows Good policyholders who moved downward into Neutral or Bad. The mechanism therefore favours recovery rather than long-term entrapment, but it also does not protect Good policyholders from downward drift entirely.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrans_summary <- clean |>\n  select(insured_id, year, bonus_score) |>\n  pivot_wider(names_from = year, values_from = bonus_score,\n              names_prefix = \"y\") |>\n  filter(!is.na(y2022), !is.na(y2024)) |>\n  mutate(\n    move = case_when(\n      y2022 == y2024 ~ \"Stayed\",\n      as.integer(y2022) < as.integer(y2024) ~ \"Worsened\",\n      TRUE ~ \"Improved\"\n    )\n  ) |>\n  count(y2022, move) |>\n  group_by(y2022) |>\n  mutate(pct = n / sum(n)) |>\n  ungroup()\n\ntrans_summary |>\n  kable(\n    caption = \"2022 to 2024 bonus-malus transitions, by starting category\",\n    digits = c(0, 0, 0, 4),\n    format.args = list(big.mark = \",\")\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: 2022 to 2024 bonus-malus transitions, by starting category\n\n|y2022   |move     |      n|    pct|\n|:-------|:--------|------:|------:|\n|Good    |Stayed   | 48,379| 0.9962|\n|Good    |Worsened |    184| 0.0038|\n|Neutral |Improved |    795| 0.8595|\n|Neutral |Stayed   |     56| 0.0605|\n|Neutral |Worsened |     74| 0.0800|\n|Bad     |Improved |    612| 0.7876|\n|Bad     |Stayed   |    165| 0.2124|\n\n\n:::\n:::\n\n\nThe transition table clarifies the pattern. Good policyholders are highly persistent, with 99.6% remaining Good between 2022 and 2024. Neutral and Bad policyholders mostly improve over the same period: 86.0% of Neutral policyholders improve, while 78.8% of Bad policyholders improve. The bonus-malus mechanism therefore appears to allow recovery from worse categories, rather than trapping policyholders there. The pricing concern surfaced in Section 4.4 is the short-term loss-ratio behaviour of policyholders while they sit in the Neutral and Bad pools, rather than any structural transition rigidity.\n\nThis result partially adjudicates the two hypotheses raised in Section 4.4. The downward-rigid transitions hypothesis is not supported by the data: policyholders in worse categories overwhelmingly improve rather than remain stuck. The default-tier under-loading hypothesis remains plausible and is consistent with the elevated short-term loss ratio observed in the Neutral pool, though confirming it would require examining the entry composition of the Neutral category over time, which sits beyond the scope of the present exercise. Future research applying a formal longitudinal model of bonus-malus dynamics could discriminate between these explanations more rigorously.\n\n\n\n## Lorenz curve of loss concentration\n\nA second question worth asking of the portfolio is how unevenly losses are distributed across the population of policies. In a perfectly homogeneous book, every policy would contribute the same share of losses. In a heterogeneous book, a small fraction of policies accounts for the bulk of incurred losses, which is what underwriters mean when they refer to a \"concentration of losses.\" The Lorenz curve visualises this.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlor <- clean |>\n  arrange(total_incurred) |>\n  mutate(\n    cum_policies = row_number() / n(),\n    cum_incurred = cumsum(total_incurred) / sum(total_incurred)\n  )\n\ngini_value <- 1 - 2 * sum((lor$cum_incurred + lag(lor$cum_incurred, default = 0)) / 2) / nrow(lor)\ngini_value <- round(gini_value, 3)\n```\n:::\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlor <- clean |>\n  arrange(total_incurred) |>\n  mutate(\n    cum_pol = row_number() / n(),\n    cum_incurred = cumsum(total_incurred) / sum(total_incurred)\n  )\n\ngini_value <- 1 - 2 * sum((lor$cum_pol[-1] - lor$cum_pol[-nrow(lor)]) *\n                            (lor$cum_incurred[-1] + lor$cum_incurred[-nrow(lor)]) / 2)\n\np90_loss_share <- 1 - lor$cum_incurred[which.min(abs(lor$cum_pol - 0.9))]\n\nggplot(lor, aes(x = cum_pol, y = cum_incurred)) +\n  geom_abline(slope = 1, intercept = 0,\n              linetype = \"dashed\", colour = house_benchmark) +\n  geom_ribbon(aes(ymin = cum_incurred, ymax = cum_pol),\n              fill = house_highlight, alpha = 0.15) +\n  geom_line(colour = house_highlight, linewidth = 1.1) +\n  annotate(\"text\",\n           x = 0.55, y = 0.62,\n           label = \"Equity line\\n(perfect equality)\",\n           hjust = 0, size = 3, colour = \"grey45\",\n           fontface = \"italic\", lineheight = 0.95) +\n  annotate(\"text\",\n           x = 0.35, y = 0.05,\n           label = paste0(\"Gini = \", round(gini_value, 3)),\n           hjust = 0, size = 5, colour = house_highlight,\n           fontface = \"bold\") +\n  annotate(\"curve\",\n           x = 0.78, xend = 0.93,\n           y = 0.18, yend = 0.28,\n           arrow = arrow(length = unit(2, \"mm\"), type = \"closed\"),\n           curvature = -0.3, colour = house_highlight, linewidth = 0.4) +\n  annotate(\"text\",\n           x = 0.77, y = 0.14,\n           label = paste0(\"Top 10% of policyholders\\nbear \",\n                          round(p90_loss_share * 100),\n                          \"% of incurred losses\"),\n           hjust = 1, size = 3.1, colour = house_highlight, lineheight = 0.95) +\n  scale_x_continuous(labels = label_percent(accuracy = 1),\n                     expand = c(0, 0)) +\n  scale_y_continuous(labels = label_percent(accuracy = 1),\n                     expand = c(0, 0)) +\n  labs(\n    title = paste0(\"Top 10% of policyholders bear \",\n                   round(p90_loss_share * 100),\n                   \"% of incurred losses\"),\n    subtitle = paste0(\"Lorenz curve of cumulative incurred losses (Gini = \",\n                      round(gini_value, 3), \")\"),\n    x = \"Cumulative share of policyholders (sorted by incurred)\",\n    y = \"Cumulative share of incurred losses\",\n    caption = \"Source: Spanish motor insurance portfolio (Mendeley Data).\"\n  ) +\n  theme_house(base_size = 11)\n```\n\n::: {.cell-output-display}\n![](TH_EX01_report_files/figure-html/unnamed-chunk-51-1.png){width=672}\n:::\n:::\n\n\nThe interpretation is direct. The dashed diagonal represents perfect equality, where the bottom X% of policies would account for X% of losses. The red curve shows reality. The bottom 85% of policies (those with no claims) contribute zero losses. The top 5% of policies account for the majority of total incurred. The Gini coefficient is approximately 0.956, indicating extreme concentration.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndecile_view <- clean |>\n  arrange(total_incurred) |>\n  mutate(decile = ntile(total_incurred, 10)) |>\n  group_by(decile) |>\n  summarise(\n    n_pol = n(),\n    share_premium = sum(total_premium) / sum(clean$total_premium),\n    share_incurred = sum(total_incurred) / sum(clean$total_incurred),\n    .groups = \"drop\"\n  )\n\ndecile_long <- decile_view |>\n  pivot_longer(c(share_premium, share_incurred),\n               names_to = \"metric\", values_to = \"share\") |>\n  mutate(metric = factor(metric,\n                          levels = c(\"share_premium\", \"share_incurred\"),\n                          labels = c(\"Share of premium\",\n                                     \"Share of incurred\")))\n\ntop10_premium <- decile_view$share_premium[10]\ntop10_incurred <- decile_view$share_incurred[10]\n\nggplot(decile_long, aes(x = factor(decile), y = share, fill = metric)) +\n  geom_col(position = position_dodge(width = 0.8), width = 0.75) +\n  geom_text(data = decile_long |> filter(decile == 10),\n            aes(label = percent(share, accuracy = 1)),\n            position = position_dodge(width = 0.8),\n            vjust = -0.5, size = 3.2, fontface = \"bold\",\n            colour = c(house_benchmark, house_highlight)) +\n  scale_y_continuous(labels = label_percent(accuracy = 1),\n                     expand = expansion(mult = c(0, 0.12))) +\n  scale_fill_manual(values = c(\"Share of premium\"  = house_benchmark,\n                                \"Share of incurred\" = house_highlight),\n                    name = NULL) +\n  labs(\n    title = paste0(\"The top decile contributes \",\n                   percent(top10_premium, accuracy = 1),\n                   \" of premium but \",\n                   percent(top10_incurred, accuracy = 1),\n                   \" of incurred losses\"),\n    subtitle = \"Premium and incurred-loss shares by decile of policies (ranked low to high by incurred losses)\",\n    x = \"Decile of policies\",\n    y = \"Share of portfolio total\",\n    caption = \"Source: Spanish motor insurance portfolio (Mendeley Data).\"\n  ) +\n  theme_house(base_size = 11) +\n  theme(legend.position = \"top\")\n```\n\n::: {.cell-output-display}\n![](TH_EX01_report_files/figure-html/unnamed-chunk-52-1.png){width=672}\n:::\n:::\n\n\nThe decile view sharpens the Lorenz finding. The top decile of policies accounts for the overwhelming share of incurred losses. The premium share contributed by the same decile is significantly smaller. The two-axis gap shows that premium charged does not currently scale with incurred losses, which is the empirical manifestation of the segment-level mismatches diagnosed in Section 4.\n\n\n## Cluster heatmap of segment risk profiles\n\nSegments examined one variable at a time can mask the multivariate structure of risk. Two segments may share a moderate loss ratio while behaving very differently on frequency, severity, and premium adequacy. A cluster heatmap addresses this by computing a multi-metric profile for each segment, standardising the metrics to a common scale, and using hierarchical clustering to group segments that share similar profiles. The dendrogram makes the clustering visible. The dendrogram is cut at k = 3 because a two-cluster cut would collapse the analytically distinct singleton into the main book, while a four-cluster cut would over-fragment the largest group without surfacing additional structure; k = 3 is the smallest cut that exposes both the high-loss singleton and the elevated-COMP_N pair.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseg_profile <- clean |>\n  filter(total_premium > 0, total_exposure > 0) |>\n  group_by(policy_type, bonus_score) |>\n  summarise(\n    n_pol      = n(),\n    loss_ratio = sum(total_incurred) / sum(total_premium),\n    frequency  = sum(total_claims) / sum(total_exposure),\n    severity   = if_else(sum(total_claims) > 0,\n                         sum(total_incurred) / sum(total_claims),\n                         NA_real_),\n    avg_prem   = sum(total_premium) / sum(total_exposure),\n    .groups = \"drop\"\n  ) |>\n  filter(n_pol >= 100, !is.na(severity)) |>\n  mutate(segment = paste(policy_type, bonus_score, sep = \" · \")) |>\n  select(segment, loss_ratio, frequency, severity, avg_prem)\n\nseg_matrix <- seg_profile |>\n  column_to_rownames(\"segment\") |>\n  scale() |>\n  as.matrix()\n```\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrow_hclust <- hclust(dist(seg_matrix),     method = \"complete\")\ncol_hclust <- hclust(dist(t(seg_matrix)),  method = \"complete\")\n\nk_row        <- 3\nrow_clusters <- cutree(row_hclust, k = k_row)\nN            <- length(row_hclust$order)\nM            <- length(col_hclust$order)\n\ncut_height <- mean(row_hclust$height[c(N - k_row, N - k_row + 1)])\n\nrow_order <- row_hclust$labels[row_hclust$order]\ncol_order <- col_hclust$labels[col_hclust$order]\n\nclassify_segment <- function(x, xend, y, yend) {\n  if (max(y, yend) >= cut_height) return(NA_character_)\n  mid_pos <- round((x + xend) / 2)\n  mid_pos <- max(1, min(N, mid_pos))\n  label   <- row_hclust$labels[row_hclust$order[mid_pos]]\n  as.character(row_clusters[label])\n}\n\nrow_ddata <- dendro_data(as.dendrogram(row_hclust), type = \"rectangle\")\nrow_segs  <- segment(row_ddata) |>\n  rowwise() |>\n  mutate(cluster = classify_segment(x, xend, y, yend)) |>\n  ungroup() |>\n  mutate(cluster = factor(cluster, levels = as.character(seq_len(k_row))))\n\ncol_ddata <- dendro_data(as.dendrogram(col_hclust), type = \"rectangle\")\ncol_segs  <- segment(col_ddata)\n\nheat_long <- seg_matrix |>\n  as.data.frame() |>\n  rownames_to_column(\"segment\") |>\n  pivot_longer(-segment, names_to = \"metric\", values_to = \"z\") |>\n  mutate(\n    segment = factor(segment, levels = row_order),\n    metric  = factor(metric,  levels = col_order)\n  )\n\ncluster_palette <- c(\"1\" = house_highlight,\n                     \"2\" = \"#4C72B0\",\n                     \"3\" = \"grey50\")\n\np_row <- ggplot(row_segs) +\n  geom_segment(aes(x = y, y = x, xend = yend, yend = xend,\n                   colour = cluster),\n               linewidth = 0.6) +\n  scale_x_reverse(expand = expansion(mult = c(0.02, 0))) +\n  scale_y_continuous(limits = c(0.5, N + 0.5),\n                     expand = c(0, 0),\n                     breaks = NULL) +\n  scale_colour_manual(values   = cluster_palette,\n                      na.value = \"grey60\",\n                      guide    = \"none\") +\n  theme_void() +\n  theme(plot.margin = margin(t = 5, r = 0, b = 30, l = 5))\n\np_col <- ggplot(col_segs) +\n  geom_segment(aes(x = x, y = y, xend = xend, yend = yend),\n               linewidth = 0.5, colour = \"grey40\") +\n  scale_x_continuous(limits = c(0.5, M + 0.5),\n                     expand = c(0, 0),\n                     breaks = NULL) +\n  scale_y_continuous(expand = expansion(mult = c(0.02, 0)),\n                     breaks = NULL) +\n  theme_void() +\n  theme(plot.margin = margin(t = 5, r = 5, b = 0, l = 0))\n\np_heat <- ggplot(heat_long, aes(x = metric, y = segment, fill = z)) +\n  geom_tile(colour = \"white\", linewidth = 0.8) +\n  geom_text(aes(label = sprintf(\"%.2f\", z)),\n            size = 2.8, colour = \"grey15\") +\n  scale_fill_gradient2(low      = \"#4C72B0\",\n                       mid      = \"white\",\n                       high     = house_highlight,\n                       midpoint = 0,\n                       name     = \"Z-score\") +\n  scale_x_discrete(expand = c(0, 0), position = \"bottom\") +\n  scale_y_discrete(expand = c(0, 0)) +\n  labs(x = NULL, y = NULL) +\n  theme_minimal(base_size = 10) +\n  theme(panel.grid        = element_blank(),\n        axis.text.x       = element_text(size = 9),\n        axis.text.y       = element_text(size = 8.5),\n        legend.position   = \"right\",\n        legend.key.height = unit(1.2, \"cm\"),\n        plot.margin       = margin(t = 5, r = 5, b = 5, l = 0))\n\n(patchwork::plot_spacer() + p_col +\n   p_row + p_heat) +\n  plot_layout(ncol = 2, widths = c(1, 4), heights = c(1, 4)) +\n  plot_annotation(\n    title    = \"Segments cluster into three distinct risk profiles\",\n    subtitle = paste0(\"Hierarchical clustering of segments and metrics \",\n                      \"(Euclidean distance, complete linkage); \",\n                      \"rows coloured by k = 3 cut\"),\n    caption  = paste0(\"Source: Spanish motor insurance portfolio (Mendeley Data).\\n\",\n                      \"Metrics scaled to z-scores prior to clustering. \",\n                      \"Branch colours indicate the three row clusters; \",\n                      \"shared trunk segments shown in grey.\"),\n    theme = theme(\n      plot.title    = element_text(face = \"bold\", size = 13),\n      plot.subtitle = element_text(colour = \"grey40\", size = 10,\n                                   margin = margin(b = 10)),\n      plot.caption  = element_text(colour = \"grey50\", size = 8, hjust = 0)\n    )\n  )\n```\n\n::: {.cell-output-display}\n![](TH_EX01_report_files/figure-html/unnamed-chunk-54-1.png){width=960}\n:::\n:::\n\n\nThe clustering algorithm groups segments by similarity across all four standardised metrics simultaneously. Three groups emerge. The largest spans eleven segments, covering TP, TPG, CC, and COMP_E across all bonus tiers, together with COMP_N · Good, all sharing balanced profiles close to the portfolio mean. The second cluster is a tight pair, COMP_N · Neutral and COMP_N · Bad, defined by elevated frequency and average premium. The third is a singleton, TPG · Bad, isolated by its very high loss ratio and severity.\nThe result sharpens the COMP_N diagnosis from Section 4.3. The elevated loss intensity is not uniform across the COMP_N product; it sits in the two bonus-malus tiers (Neutral and Bad) where Section 4.4 already identified premium inadequacy. The clustering and the bonus-malus paradox therefore point to the same pattern from two angles. The dendrogram quantifies the separations: the largest vertical jump isolates TPG · Bad, with the COMP_N · Neutral and COMP_N · Bad pair separating from the main group at the next level down.\n\n# Summary\n\nThis analysis of a Spanish motor insurance portfolio across 2022 to 2024 examined the distributional shape of policy, vehicle, driver, and geographic characteristics, and investigated bivariate relationships with portfolio profitability and volatility. The key findings are summarised below.\n\n## Key findings\n\n- The portfolio loss ratio rose from 65.7 percent in 2022 to 74.7 percent in 2024. The deterioration is statistically validated through non-overlapping bootstrap confidence intervals, and a within-versus-between decomposition shows that 8.5 of the 8.9-percentage-point swing arises from within-segment deterioration rather than from a mix shift toward worse-performing segments. Claim severity rather than claim frequency dominates the aggregate trend.\n- Loss ratio varies monotonically across coverage tiers, from 54 percent in basic third-party to approximately 94 percent in comprehensive-without-excess (COMP_N). Pairwise non-parametric tests confirm that COMP_N is statistically distinct from every other tier.\n- The bonus-malus categories show an unexpected pattern: the Neutral tier carries a higher loss ratio than the Bad tier despite collecting less premium per exposure. Frequency rises monotonically across the three categories as expected, but the loss-ratio ordering inverts at the top.\n- Geographic loss intensity differs sharply within municipality categories. Urban island policies run 11 percentage points above rural island policies, the widest within-category spread in the geographic dimension.\n- Driver age and vehicle age interact non-additively in their relationship with loss ratio. The under-25 driver band paired with older vehicles shows the highest loss intensity in the joint surface.\n- Coverage tier and bonus-malus interact in the multivariate clustering. The elevated loss profile is not uniform across COMP_N: it concentrates in the Neutral and Bad bonus tiers, which cluster as a tight pair, while COMP_N · Good sits with the main book. The clustering corroborates the bonus-malus paradox identified in Section 4.4 from a different methodological angle.\n- Loss concentration is extreme. The Lorenz curve of incurred losses yields a Gini coefficient of approximately 0.96, with the top decile of policies bearing approximately 99 percent of total incurred losses.\n\n## Recommendations for future research\n\n- **Confirmatory analysis.** This study is exploratory. Future work should apply formal causal-inference methods to confirm whether the segment-level loss-ratio differences reflect underlying risk heterogeneity or unobserved confounding.\n- **Additional variables.** The Mendeley dataset is rich on policy and vehicle characteristics but contains no driving-behaviour telematics, no claim-type detail beyond seven coverage categories, and no geographic granularity below the municipality type. Incorporating these would refine the segment-level diagnostics.\n- **Longitudinal modelling.** The panel structure used in the Sankey analysis could be extended to a full longitudinal model of policyholder transitions, including survival analysis of policy cancellation and Markov chain modelling of bonus-malus dynamics. Such a model would discriminate between the two hypotheses raised in Section 4.4 (default-tier under-loading versus claims-history dynamics) more rigorously than the present cross-sectional decomposition permits.\n- **External benchmarking.** Comparing the observed loss ratios and segment patterns against published Spanish motor market benchmarks would clarify whether the findings are portfolio-specific or generalisable.\n- **Missingness mechanism**. The 1,800 records dropped via listwise deletion show slightly higher premium and claim rate than the retained population. Future work could apply multiple imputation or model the missingness explicitly to test whether the findings are robust to alternative treatments.\n\n\n## Methodological reflection\n\nThe exercise demonstrates that visual analytics serves three distinct functions in a portfolio review. The first is descriptive, characterising the shape and concentration of the variables that constitute the book. The second is diagnostic, surfacing the segments where premium and exposure are out of balance. The third is communicative, presenting findings in a form that supports further investigation. The bonus methods applied in Section 5 illustrate that the most informative approaches sometimes exploit data-structural features (panel observation, concentration of loss, multivariate clustering) rather than summarising marginal distributions.\n\n## Session information\n\nThe R session details below document the exact computing environment used to produce this report.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n## R version 4.5.3 (2026-03-11 ucrt)\n## Platform: x86_64-w64-mingw32/x64\n## Running under: Windows 11 x64 (build 26200)\n## \n## Matrix products: default\n##   LAPACK version 3.12.1\n## \n## locale:\n## [1] LC_COLLATE=English_Singapore.utf8  LC_CTYPE=English_Singapore.utf8   \n## [3] LC_MONETARY=English_Singapore.utf8 LC_NUMERIC=C                      \n## [5] LC_TIME=English_Singapore.utf8    \n## \n## time zone: Asia/Singapore\n## tzcode source: internal\n## \n## attached base packages:\n## [1] stats     graphics  grDevices utils     datasets  methods   base     \n## \n## other attached packages:\n##  [1] knitr_1.51         scales_1.4.0       patchwork_1.3.2    ggrepel_0.9.8     \n##  [5] ggdendro_0.2.0     ggalluvial_0.12.6  ggcorrplot_0.1.4.1 ggridges_0.5.7    \n##  [9] ggdist_3.3.3       ggstatsplot_1.0.0  naniar_1.1.0       skimr_2.2.2       \n## [13] janitor_2.2.1      readxl_1.4.5       lubridate_1.9.5    forcats_1.0.1     \n## [17] stringr_1.6.0      dplyr_1.2.1        purrr_1.2.2        readr_2.2.0       \n## [21] tidyr_1.3.2        tibble_3.3.1       ggplot2_4.0.2      tidyverse_2.0.0   \n## \n## loaded via a namespace (and not attached):\n##  [1] tidyselect_1.2.1       Rmpfr_1.1-2            farver_2.1.2          \n##  [4] statsExpressions_2.0.0 S7_0.2.1               fastmap_1.2.0         \n##  [7] pacman_0.5.1           bayestestR_0.17.0      digest_0.6.39         \n## [10] timechange_0.4.0       lifecycle_1.0.5        multcompView_0.1-11   \n## [13] magrittr_2.0.5         compiler_4.5.3         rlang_1.2.0           \n## [16] tools_4.5.3            yaml_2.3.12            ggsignif_0.6.4        \n## [19] labeling_0.4.3         htmlwidgets_1.6.4      bit_4.6.0             \n## [22] plyr_1.8.9             repr_1.1.7             RColorBrewer_1.1-3    \n## [25] SuppDists_1.1-9.9      withr_3.0.2            grid_4.5.3            \n## [28] datawizard_1.3.1       paletteer_1.7.0        MASS_7.3-65           \n## [31] insight_1.5.0          mvtnorm_1.3-7          cli_3.6.5             \n## [34] rmarkdown_2.31         crayon_1.5.3           generics_0.1.4        \n## [37] otel_0.2.0             RcppParallel_5.1.11-2  rstudioapi_0.18.0     \n## [40] reshape2_1.4.5         tzdb_0.5.0             parameters_0.28.3     \n## [43] cachem_1.1.0           parallel_4.5.3         effectsize_1.0.2      \n## [46] cellranger_1.1.0       base64enc_0.1-6        vctrs_0.7.2           \n## [49] boot_1.3-32            jsonlite_2.0.0         hms_1.1.4             \n## [52] bit64_4.6.0-1          visdat_0.6.0           correlation_0.8.8     \n## [55] BWStest_0.2.3          PMCMRplus_1.9.12       glue_1.8.1            \n## [58] rematch2_2.1.2         distributional_0.7.0   stringi_1.8.7         \n## [61] gtable_0.3.6           gmp_0.7-5.1            pillar_1.11.1         \n## [64] htmltools_0.5.9        R6_2.6.1               vroom_1.7.1           \n## [67] evaluate_1.0.5         memoise_2.0.1          snakecase_0.11.1      \n## [70] rstantools_2.6.0       Rcpp_1.1.1             xfun_0.57             \n## [73] kSamples_1.2-12        pkgconfig_2.0.3\n```\n:::\n\n\n\n# References\n\n-   Kam, T. S. (2024). *R for Visual Analytics*. <https://r4va.netlify.app/>\n-   Swiss Re Institute (2019). *sigma 4/2019: Advanced analytics: unlocking new frontiers in P&C insurance.* Zurich: Swiss Re Management Ltd.\n-   Mendeley Data. *Spanish motor vehicle insurance portfolio dataset.*\n-   Wickham, H. et al. (2019). Welcome to the Tidyverse. *Journal of Open Source Software*, 4(43), 1686.\n-   Patil, I. (2021). Visualizations with statistical details: The ggstatsplot approach. *Journal of Open Source Software*, 6(61), 3167.\n-   Kay, M. (2024). ggdist: Visualizations of Distributions and Uncertainty. *R package version 3.3.2*.\n-   Brunson, J. C. (2020). ggalluvial: Layered Grammar for Alluvial Plots. *Journal of Open Source Software*, 5(49), 2017.\n-   Kassambara, A. (2023). ggcorrplot: Visualization of a Correlation Matrix using ggplot2. *R package version 0.1.4.1*.\n\n",
    "supporting": [
      "TH_EX01_report_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}